// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/exporttype"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ExportType is the model entity for the ExportType schema.
type ExportType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExportTypeQuery when eager-loading is set.
	Edges        ExportTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExportTypeEdges holds the relations/edges for other nodes in the graph.
type ExportTypeEdges struct {
	// ExportLogs holds the value of the export_logs edge.
	ExportLogs []*ExportLog `json:"export_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ExportLogsOrErr returns the ExportLogs value or an error if the edge
// was not loaded in eager-loading.
func (e ExportTypeEdges) ExportLogsOrErr() ([]*ExportLog, error) {
	if e.loadedTypes[0] {
		return e.ExportLogs, nil
	}
	return nil, &NotLoadedError{edge: "export_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExportType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exporttype.FieldID:
			values[i] = new(sql.NullInt64)
		case exporttype.FieldCode:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExportType fields.
func (_m *ExportType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exporttype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case exporttype.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExportType.
// This includes values selected through modifiers, order, etc.
func (_m *ExportType) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExportLogs queries the "export_logs" edge of the ExportType entity.
func (_m *ExportType) QueryExportLogs() *ExportLogQuery {
	return NewExportTypeClient(_m.config).QueryExportLogs(_m)
}

// Update returns a builder for updating this ExportType.
// Note that you need to call ExportType.Unwrap() before calling this method if this ExportType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExportType) Update() *ExportTypeUpdateOne {
	return NewExportTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExportType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExportType) Unwrap() *ExportType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExportType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExportType) String() string {
	var builder strings.Builder
	builder.WriteString("ExportType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteByte(')')
	return builder.String()
}

// ExportTypes is a parsable slice of ExportType.
type ExportTypes []*ExportType
