// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/exportlog"
	"asutp-server/ent/exporttype"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExportTypeCreate is the builder for creating a ExportType entity.
type ExportTypeCreate struct {
	config
	mutation *ExportTypeMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *ExportTypeCreate) SetCode(v string) *ExportTypeCreate {
	_c.mutation.SetCode(v)
	return _c
}

// AddExportLogIDs adds the "export_logs" edge to the ExportLog entity by IDs.
func (_c *ExportTypeCreate) AddExportLogIDs(ids ...int) *ExportTypeCreate {
	_c.mutation.AddExportLogIDs(ids...)
	return _c
}

// AddExportLogs adds the "export_logs" edges to the ExportLog entity.
func (_c *ExportTypeCreate) AddExportLogs(v ...*ExportLog) *ExportTypeCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddExportLogIDs(ids...)
}

// Mutation returns the ExportTypeMutation object of the builder.
func (_c *ExportTypeCreate) Mutation() *ExportTypeMutation {
	return _c.mutation
}

// Save creates the ExportType in the database.
func (_c *ExportTypeCreate) Save(ctx context.Context) (*ExportType, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExportTypeCreate) SaveX(ctx context.Context) *ExportType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExportTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExportTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExportTypeCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ExportType.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := exporttype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ExportType.code": %w`, err)}
		}
	}
	return nil
}

func (_c *ExportTypeCreate) sqlSave(ctx context.Context) (*ExportType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExportTypeCreate) createSpec() (*ExportType, *sqlgraph.CreateSpec) {
	var (
		_node = &ExportType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exporttype.Table, sqlgraph.NewFieldSpec(exporttype.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(exporttype.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if nodes := _c.mutation.ExportLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exporttype.ExportLogsTable,
			Columns: []string{exporttype.ExportLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exportlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExportTypeCreateBulk is the builder for creating many ExportType entities in bulk.
type ExportTypeCreateBulk struct {
	config
	err      error
	builders []*ExportTypeCreate
}

// Save creates the ExportType entities in the database.
func (_c *ExportTypeCreateBulk) Save(ctx context.Context) ([]*ExportType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExportType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExportTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExportTypeCreateBulk) SaveX(ctx context.Context) []*ExportType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExportTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExportTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
