// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/exportlog"
	"asutp-server/ent/exporttype"
	"asutp-server/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ExportLog is the model entity for the ExportLog schema.
type ExportLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// ExportTypeID holds the value of the "export_type_id" field.
	ExportTypeID int `json:"export_type_id,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName *string `json:"file_name,omitempty"`
	// RecordCount holds the value of the "record_count" field.
	RecordCount *int `json:"record_count,omitempty"`
	// ExportedAt holds the value of the "exported_at" field.
	ExportedAt time.Time `json:"exported_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExportLogQuery when eager-loading is set.
	Edges        ExportLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExportLogEdges holds the relations/edges for other nodes in the graph.
type ExportLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// ExportType holds the value of the export_type edge.
	ExportType *ExportType `json:"export_type,omitempty"`
	// ExportLogTasks holds the value of the export_log_tasks edge.
	ExportLogTasks []*ExportLogTask `json:"export_log_tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExportLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ExportTypeOrErr returns the ExportType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExportLogEdges) ExportTypeOrErr() (*ExportType, error) {
	if e.ExportType != nil {
		return e.ExportType, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: exporttype.Label}
	}
	return nil, &NotLoadedError{edge: "export_type"}
}

// ExportLogTasksOrErr returns the ExportLogTasks value or an error if the edge
// was not loaded in eager-loading.
func (e ExportLogEdges) ExportLogTasksOrErr() ([]*ExportLogTask, error) {
	if e.loadedTypes[2] {
		return e.ExportLogTasks, nil
	}
	return nil, &NotLoadedError{edge: "export_log_tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExportLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exportlog.FieldID, exportlog.FieldUserID, exportlog.FieldExportTypeID, exportlog.FieldRecordCount:
			values[i] = new(sql.NullInt64)
		case exportlog.FieldFileName:
			values[i] = new(sql.NullString)
		case exportlog.FieldExportedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExportLog fields.
func (_m *ExportLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exportlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case exportlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case exportlog.FieldExportTypeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field export_type_id", values[i])
			} else if value.Valid {
				_m.ExportTypeID = int(value.Int64)
			}
		case exportlog.FieldFileName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[i])
			} else if value.Valid {
				_m.FileName = new(string)
				*_m.FileName = value.String
			}
		case exportlog.FieldRecordCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field record_count", values[i])
			} else if value.Valid {
				_m.RecordCount = new(int)
				*_m.RecordCount = int(value.Int64)
			}
		case exportlog.FieldExportedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field exported_at", values[i])
			} else if value.Valid {
				_m.ExportedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExportLog.
// This includes values selected through modifiers, order, etc.
func (_m *ExportLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ExportLog entity.
func (_m *ExportLog) QueryUser() *UserQuery {
	return NewExportLogClient(_m.config).QueryUser(_m)
}

// QueryExportType queries the "export_type" edge of the ExportLog entity.
func (_m *ExportLog) QueryExportType() *ExportTypeQuery {
	return NewExportLogClient(_m.config).QueryExportType(_m)
}

// QueryExportLogTasks queries the "export_log_tasks" edge of the ExportLog entity.
func (_m *ExportLog) QueryExportLogTasks() *ExportLogTaskQuery {
	return NewExportLogClient(_m.config).QueryExportLogTasks(_m)
}

// Update returns a builder for updating this ExportLog.
// Note that you need to call ExportLog.Unwrap() before calling this method if this ExportLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExportLog) Update() *ExportLogUpdateOne {
	return NewExportLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExportLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExportLog) Unwrap() *ExportLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExportLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExportLog) String() string {
	var builder strings.Builder
	builder.WriteString("ExportLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("export_type_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExportTypeID))
	builder.WriteString(", ")
	if v := _m.FileName; v != nil {
		builder.WriteString("file_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RecordCount; v != nil {
		builder.WriteString("record_count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("exported_at=")
	builder.WriteString(_m.ExportedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ExportLogs is a parsable slice of ExportLog.
type ExportLogs []*ExportLog
