// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/exportlog"
	"asutp-server/ent/exportlogtask"
	"asutp-server/ent/task"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExportLogTaskCreate is the builder for creating a ExportLogTask entity.
type ExportLogTaskCreate struct {
	config
	mutation *ExportLogTaskMutation
	hooks    []Hook
}

// SetExportLogID sets the "export_log_id" field.
func (_c *ExportLogTaskCreate) SetExportLogID(v int) *ExportLogTaskCreate {
	_c.mutation.SetExportLogID(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *ExportLogTaskCreate) SetTaskID(v int) *ExportLogTaskCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetExportLog sets the "export_log" edge to the ExportLog entity.
func (_c *ExportLogTaskCreate) SetExportLog(v *ExportLog) *ExportLogTaskCreate {
	return _c.SetExportLogID(v.ID)
}

// SetTask sets the "task" edge to the Task entity.
func (_c *ExportLogTaskCreate) SetTask(v *Task) *ExportLogTaskCreate {
	return _c.SetTaskID(v.ID)
}

// Mutation returns the ExportLogTaskMutation object of the builder.
func (_c *ExportLogTaskCreate) Mutation() *ExportLogTaskMutation {
	return _c.mutation
}

// Save creates the ExportLogTask in the database.
func (_c *ExportLogTaskCreate) Save(ctx context.Context) (*ExportLogTask, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExportLogTaskCreate) SaveX(ctx context.Context) *ExportLogTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExportLogTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExportLogTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExportLogTaskCreate) check() error {
	if _, ok := _c.mutation.ExportLogID(); !ok {
		return &ValidationError{Name: "export_log_id", err: errors.New(`ent: missing required field "ExportLogTask.export_log_id"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "ExportLogTask.task_id"`)}
	}
	if len(_c.mutation.ExportLogIDs()) == 0 {
		return &ValidationError{Name: "export_log", err: errors.New(`ent: missing required edge "ExportLogTask.export_log"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "ExportLogTask.task"`)}
	}
	return nil
}

func (_c *ExportLogTaskCreate) sqlSave(ctx context.Context) (*ExportLogTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExportLogTaskCreate) createSpec() (*ExportLogTask, *sqlgraph.CreateSpec) {
	var (
		_node = &ExportLogTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(exportlogtask.Table, sqlgraph.NewFieldSpec(exportlogtask.FieldID, field.TypeInt))
	)
	if nodes := _c.mutation.ExportLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   exportlogtask.ExportLogTable,
			Columns: []string{exportlogtask.ExportLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exportlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExportLogID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   exportlogtask.TaskTable,
			Columns: []string{exportlogtask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ExportLogTaskCreateBulk is the builder for creating many ExportLogTask entities in bulk.
type ExportLogTaskCreateBulk struct {
	config
	err      error
	builders []*ExportLogTaskCreate
}

// Save creates the ExportLogTask entities in the database.
func (_c *ExportLogTaskCreateBulk) Save(ctx context.Context) ([]*ExportLogTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExportLogTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExportLogTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExportLogTaskCreateBulk) SaveX(ctx context.Context) []*ExportLogTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExportLogTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExportLogTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
