// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/exportlog"
	"asutp-server/ent/exporttype"
	"asutp-server/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExportTypeUpdate is the builder for updating ExportType entities.
type ExportTypeUpdate struct {
	config
	hooks    []Hook
	mutation *ExportTypeMutation
}

// Where appends a list predicates to the ExportTypeUpdate builder.
func (_u *ExportTypeUpdate) Where(ps ...predicate.ExportType) *ExportTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *ExportTypeUpdate) SetCode(v string) *ExportTypeUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ExportTypeUpdate) SetNillableCode(v *string) *ExportTypeUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// AddExportLogIDs adds the "export_logs" edge to the ExportLog entity by IDs.
func (_u *ExportTypeUpdate) AddExportLogIDs(ids ...int) *ExportTypeUpdate {
	_u.mutation.AddExportLogIDs(ids...)
	return _u
}

// AddExportLogs adds the "export_logs" edges to the ExportLog entity.
func (_u *ExportTypeUpdate) AddExportLogs(v ...*ExportLog) *ExportTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExportLogIDs(ids...)
}

// Mutation returns the ExportTypeMutation object of the builder.
func (_u *ExportTypeUpdate) Mutation() *ExportTypeMutation {
	return _u.mutation
}

// ClearExportLogs clears all "export_logs" edges to the ExportLog entity.
func (_u *ExportTypeUpdate) ClearExportLogs() *ExportTypeUpdate {
	_u.mutation.ClearExportLogs()
	return _u
}

// RemoveExportLogIDs removes the "export_logs" edge to ExportLog entities by IDs.
func (_u *ExportTypeUpdate) RemoveExportLogIDs(ids ...int) *ExportTypeUpdate {
	_u.mutation.RemoveExportLogIDs(ids...)
	return _u
}

// RemoveExportLogs removes "export_logs" edges to ExportLog entities.
func (_u *ExportTypeUpdate) RemoveExportLogs(v ...*ExportLog) *ExportTypeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExportLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExportTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExportTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExportTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExportTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExportTypeUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := exporttype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ExportType.code": %w`, err)}
		}
	}
	return nil
}

func (_u *ExportTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exporttype.Table, exporttype.Columns, sqlgraph.NewFieldSpec(exporttype.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(exporttype.FieldCode, field.TypeString, value)
	}
	if _u.mutation.ExportLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exporttype.ExportLogsTable,
			Columns: []string{exporttype.ExportLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exportlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExportLogsIDs(); len(nodes) > 0 && !_u.mutation.ExportLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exporttype.ExportLogsTable,
			Columns: []string{exporttype.ExportLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exportlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExportLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exporttype.ExportLogsTable,
			Columns: []string{exporttype.ExportLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exportlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exporttype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExportTypeUpdateOne is the builder for updating a single ExportType entity.
type ExportTypeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExportTypeMutation
}

// SetCode sets the "code" field.
func (_u *ExportTypeUpdateOne) SetCode(v string) *ExportTypeUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ExportTypeUpdateOne) SetNillableCode(v *string) *ExportTypeUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// AddExportLogIDs adds the "export_logs" edge to the ExportLog entity by IDs.
func (_u *ExportTypeUpdateOne) AddExportLogIDs(ids ...int) *ExportTypeUpdateOne {
	_u.mutation.AddExportLogIDs(ids...)
	return _u
}

// AddExportLogs adds the "export_logs" edges to the ExportLog entity.
func (_u *ExportTypeUpdateOne) AddExportLogs(v ...*ExportLog) *ExportTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExportLogIDs(ids...)
}

// Mutation returns the ExportTypeMutation object of the builder.
func (_u *ExportTypeUpdateOne) Mutation() *ExportTypeMutation {
	return _u.mutation
}

// ClearExportLogs clears all "export_logs" edges to the ExportLog entity.
func (_u *ExportTypeUpdateOne) ClearExportLogs() *ExportTypeUpdateOne {
	_u.mutation.ClearExportLogs()
	return _u
}

// RemoveExportLogIDs removes the "export_logs" edge to ExportLog entities by IDs.
func (_u *ExportTypeUpdateOne) RemoveExportLogIDs(ids ...int) *ExportTypeUpdateOne {
	_u.mutation.RemoveExportLogIDs(ids...)
	return _u
}

// RemoveExportLogs removes "export_logs" edges to ExportLog entities.
func (_u *ExportTypeUpdateOne) RemoveExportLogs(v ...*ExportLog) *ExportTypeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExportLogIDs(ids...)
}

// Where appends a list predicates to the ExportTypeUpdate builder.
func (_u *ExportTypeUpdateOne) Where(ps ...predicate.ExportType) *ExportTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExportTypeUpdateOne) Select(field string, fields ...string) *ExportTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ExportType entity.
func (_u *ExportTypeUpdateOne) Save(ctx context.Context) (*ExportType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExportTypeUpdateOne) SaveX(ctx context.Context) *ExportType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExportTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExportTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExportTypeUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := exporttype.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "ExportType.code": %w`, err)}
		}
	}
	return nil
}

func (_u *ExportTypeUpdateOne) sqlSave(ctx context.Context) (_node *ExportType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(exporttype.Table, exporttype.Columns, sqlgraph.NewFieldSpec(exporttype.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExportType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, exporttype.FieldID)
		for _, f := range fields {
			if !exporttype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != exporttype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(exporttype.FieldCode, field.TypeString, value)
	}
	if _u.mutation.ExportLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exporttype.ExportLogsTable,
			Columns: []string{exporttype.ExportLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exportlog.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExportLogsIDs(); len(nodes) > 0 && !_u.mutation.ExportLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exporttype.ExportLogsTable,
			Columns: []string{exporttype.ExportLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exportlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExportLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   exporttype.ExportLogsTable,
			Columns: []string{exporttype.ExportLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(exportlog.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ExportType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{exporttype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
