// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/exportlog"
	"asutp-server/ent/exportlogtask"
	"asutp-server/ent/task"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ExportLogTask is the model entity for the ExportLogTask schema.
type ExportLogTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ExportLogID holds the value of the "export_log_id" field.
	ExportLogID int `json:"export_log_id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID int `json:"task_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExportLogTaskQuery when eager-loading is set.
	Edges        ExportLogTaskEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExportLogTaskEdges holds the relations/edges for other nodes in the graph.
type ExportLogTaskEdges struct {
	// ExportLog holds the value of the export_log edge.
	ExportLog *ExportLog `json:"export_log,omitempty"`
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ExportLogOrErr returns the ExportLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExportLogTaskEdges) ExportLogOrErr() (*ExportLog, error) {
	if e.ExportLog != nil {
		return e.ExportLog, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: exportlog.Label}
	}
	return nil, &NotLoadedError{edge: "export_log"}
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ExportLogTaskEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExportLogTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case exportlogtask.FieldID, exportlogtask.FieldExportLogID, exportlogtask.FieldTaskID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExportLogTask fields.
func (_m *ExportLogTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case exportlogtask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case exportlogtask.FieldExportLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field export_log_id", values[i])
			} else if value.Valid {
				_m.ExportLogID = int(value.Int64)
			}
		case exportlogtask.FieldTaskID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExportLogTask.
// This includes values selected through modifiers, order, etc.
func (_m *ExportLogTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryExportLog queries the "export_log" edge of the ExportLogTask entity.
func (_m *ExportLogTask) QueryExportLog() *ExportLogQuery {
	return NewExportLogTaskClient(_m.config).QueryExportLog(_m)
}

// QueryTask queries the "task" edge of the ExportLogTask entity.
func (_m *ExportLogTask) QueryTask() *TaskQuery {
	return NewExportLogTaskClient(_m.config).QueryTask(_m)
}

// Update returns a builder for updating this ExportLogTask.
// Note that you need to call ExportLogTask.Unwrap() before calling this method if this ExportLogTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExportLogTask) Update() *ExportLogTaskUpdateOne {
	return NewExportLogTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExportLogTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExportLogTask) Unwrap() *ExportLogTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExportLogTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExportLogTask) String() string {
	var builder strings.Builder
	builder.WriteString("ExportLogTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("export_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExportLogID))
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteByte(')')
	return builder.String()
}

// ExportLogTasks is a parsable slice of ExportLogTask.
type ExportLogTasks []*ExportLogTask
