// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/kpi"
	"asutp-server/ent/task"
	"asutp-server/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Kpi is the model entity for the Kpi schema.
type Kpi struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID int `json:"task_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Score holds the value of the "score" field.
	Score float64 `json:"score,omitempty"`
	// IsConfirmed holds the value of the "is_confirmed" field.
	IsConfirmed bool `json:"is_confirmed,omitempty"`
	// ConfirmedAt holds the value of the "confirmed_at" field.
	ConfirmedAt *time.Time `json:"confirmed_at,omitempty"`
	// ConfirmedBy holds the value of the "confirmed_by" field.
	ConfirmedBy *int `json:"confirmed_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the KpiQuery when eager-loading is set.
	Edges        KpiEdges `json:"edges"`
	selectValues sql.SelectValues
}

// KpiEdges holds the relations/edges for other nodes in the graph.
type KpiEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Confirmer holds the value of the confirmer edge.
	Confirmer *User `json:"confirmer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e KpiEdges) TaskOrErr() (*Task, error) {
	if e.Task != nil {
		return e.Task, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "task"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e KpiEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ConfirmerOrErr returns the Confirmer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e KpiEdges) ConfirmerOrErr() (*User, error) {
	if e.Confirmer != nil {
		return e.Confirmer, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "confirmer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Kpi) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case kpi.FieldIsConfirmed:
			values[i] = new(sql.NullBool)
		case kpi.FieldScore:
			values[i] = new(sql.NullFloat64)
		case kpi.FieldID, kpi.FieldTaskID, kpi.FieldUserID, kpi.FieldConfirmedBy:
			values[i] = new(sql.NullInt64)
		case kpi.FieldConfirmedAt, kpi.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Kpi fields.
func (_m *Kpi) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kpi.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case kpi.FieldTaskID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = int(value.Int64)
			}
		case kpi.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case kpi.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = value.Float64
			}
		case kpi.FieldIsConfirmed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_confirmed", values[i])
			} else if value.Valid {
				_m.IsConfirmed = value.Bool
			}
		case kpi.FieldConfirmedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_at", values[i])
			} else if value.Valid {
				_m.ConfirmedAt = new(time.Time)
				*_m.ConfirmedAt = value.Time
			}
		case kpi.FieldConfirmedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field confirmed_by", values[i])
			} else if value.Valid {
				_m.ConfirmedBy = new(int)
				*_m.ConfirmedBy = int(value.Int64)
			}
		case kpi.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Kpi.
// This includes values selected through modifiers, order, etc.
func (_m *Kpi) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the Kpi entity.
func (_m *Kpi) QueryTask() *TaskQuery {
	return NewKpiClient(_m.config).QueryTask(_m)
}

// QueryUser queries the "user" edge of the Kpi entity.
func (_m *Kpi) QueryUser() *UserQuery {
	return NewKpiClient(_m.config).QueryUser(_m)
}

// QueryConfirmer queries the "confirmer" edge of the Kpi entity.
func (_m *Kpi) QueryConfirmer() *UserQuery {
	return NewKpiClient(_m.config).QueryConfirmer(_m)
}

// Update returns a builder for updating this Kpi.
// Note that you need to call Kpi.Unwrap() before calling this method if this Kpi
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Kpi) Update() *KpiUpdateOne {
	return NewKpiClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Kpi entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Kpi) Unwrap() *Kpi {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Kpi is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Kpi) String() string {
	var builder strings.Builder
	builder.WriteString("Kpi(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("is_confirmed=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsConfirmed))
	builder.WriteString(", ")
	if v := _m.ConfirmedAt; v != nil {
		builder.WriteString("confirmed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ConfirmedBy; v != nil {
		builder.WriteString("confirmed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Kpis is a parsable slice of Kpi.
type Kpis []*Kpi
