// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/predicate"
	"asutp-server/ent/task"
	"asutp-server/ent/taskassignee"
	"asutp-server/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskAssigneeUpdate is the builder for updating TaskAssignee entities.
type TaskAssigneeUpdate struct {
	config
	hooks    []Hook
	mutation *TaskAssigneeMutation
}

// Where appends a list predicates to the TaskAssigneeUpdate builder.
func (_u *TaskAssigneeUpdate) Where(ps ...predicate.TaskAssignee) *TaskAssigneeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskAssigneeUpdate) SetStatus(v string) *TaskAssigneeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskAssigneeUpdate) SetNillableStatus(v *string) *TaskAssigneeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *TaskAssigneeUpdate) SetApprovedAt(v time.Time) *TaskAssigneeUpdate {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *TaskAssigneeUpdate) SetNillableApprovedAt(v *time.Time) *TaskAssigneeUpdate {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *TaskAssigneeUpdate) ClearApprovedAt() *TaskAssigneeUpdate {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *TaskAssigneeUpdate) SetTaskID(v int) *TaskAssigneeUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskAssigneeUpdate) SetNillableTaskID(v *int) *TaskAssigneeUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TaskAssigneeUpdate) SetUserID(v int) *TaskAssigneeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TaskAssigneeUpdate) SetNillableUserID(v *int) *TaskAssigneeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProposerID sets the "proposer_id" field.
func (_u *TaskAssigneeUpdate) SetProposerID(v int) *TaskAssigneeUpdate {
	_u.mutation.SetProposerID(v)
	return _u
}

// SetNillableProposerID sets the "proposer_id" field if the given value is not nil.
func (_u *TaskAssigneeUpdate) SetNillableProposerID(v *int) *TaskAssigneeUpdate {
	if v != nil {
		_u.SetProposerID(*v)
	}
	return _u
}

// SetApproverID sets the "approver_id" field.
func (_u *TaskAssigneeUpdate) SetApproverID(v int) *TaskAssigneeUpdate {
	_u.mutation.SetApproverID(v)
	return _u
}

// SetNillableApproverID sets the "approver_id" field if the given value is not nil.
func (_u *TaskAssigneeUpdate) SetNillableApproverID(v *int) *TaskAssigneeUpdate {
	if v != nil {
		_u.SetApproverID(*v)
	}
	return _u
}

// ClearApproverID clears the value of the "approver_id" field.
func (_u *TaskAssigneeUpdate) ClearApproverID() *TaskAssigneeUpdate {
	_u.mutation.ClearApproverID()
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskAssigneeUpdate) SetTask(v *Task) *TaskAssigneeUpdate {
	return _u.SetTaskID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TaskAssigneeUpdate) SetUser(v *User) *TaskAssigneeUpdate {
	return _u.SetUserID(v.ID)
}

// SetProposer sets the "proposer" edge to the User entity.
func (_u *TaskAssigneeUpdate) SetProposer(v *User) *TaskAssigneeUpdate {
	return _u.SetProposerID(v.ID)
}

// SetApprover sets the "approver" edge to the User entity.
func (_u *TaskAssigneeUpdate) SetApprover(v *User) *TaskAssigneeUpdate {
	return _u.SetApproverID(v.ID)
}

// Mutation returns the TaskAssigneeMutation object of the builder.
func (_u *TaskAssigneeUpdate) Mutation() *TaskAssigneeMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskAssigneeUpdate) ClearTask() *TaskAssigneeUpdate {
	_u.mutation.ClearTask()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TaskAssigneeUpdate) ClearUser() *TaskAssigneeUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearProposer clears the "proposer" edge to the User entity.
func (_u *TaskAssigneeUpdate) ClearProposer() *TaskAssigneeUpdate {
	_u.mutation.ClearProposer()
	return _u
}

// ClearApprover clears the "approver" edge to the User entity.
func (_u *TaskAssigneeUpdate) ClearApprover() *TaskAssigneeUpdate {
	_u.mutation.ClearApprover()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskAssigneeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskAssigneeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskAssigneeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskAssigneeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskAssigneeUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := taskassignee.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TaskAssignee.status": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskAssignee.task"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskAssignee.user"`)
	}
	if _u.mutation.ProposerCleared() && len(_u.mutation.ProposerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskAssignee.proposer"`)
	}
	return nil
}

func (_u *TaskAssigneeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskassignee.Table, taskassignee.Columns, sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(taskassignee.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(taskassignee.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(taskassignee.FieldApprovedAt, field.TypeTime)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProposerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProposerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApproverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApproverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskassignee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskAssigneeUpdateOne is the builder for updating a single TaskAssignee entity.
type TaskAssigneeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskAssigneeMutation
}

// SetStatus sets the "status" field.
func (_u *TaskAssigneeUpdateOne) SetStatus(v string) *TaskAssigneeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskAssigneeUpdateOne) SetNillableStatus(v *string) *TaskAssigneeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *TaskAssigneeUpdateOne) SetApprovedAt(v time.Time) *TaskAssigneeUpdateOne {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *TaskAssigneeUpdateOne) SetNillableApprovedAt(v *time.Time) *TaskAssigneeUpdateOne {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *TaskAssigneeUpdateOne) ClearApprovedAt() *TaskAssigneeUpdateOne {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *TaskAssigneeUpdateOne) SetTaskID(v int) *TaskAssigneeUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskAssigneeUpdateOne) SetNillableTaskID(v *int) *TaskAssigneeUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TaskAssigneeUpdateOne) SetUserID(v int) *TaskAssigneeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TaskAssigneeUpdateOne) SetNillableUserID(v *int) *TaskAssigneeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProposerID sets the "proposer_id" field.
func (_u *TaskAssigneeUpdateOne) SetProposerID(v int) *TaskAssigneeUpdateOne {
	_u.mutation.SetProposerID(v)
	return _u
}

// SetNillableProposerID sets the "proposer_id" field if the given value is not nil.
func (_u *TaskAssigneeUpdateOne) SetNillableProposerID(v *int) *TaskAssigneeUpdateOne {
	if v != nil {
		_u.SetProposerID(*v)
	}
	return _u
}

// SetApproverID sets the "approver_id" field.
func (_u *TaskAssigneeUpdateOne) SetApproverID(v int) *TaskAssigneeUpdateOne {
	_u.mutation.SetApproverID(v)
	return _u
}

// SetNillableApproverID sets the "approver_id" field if the given value is not nil.
func (_u *TaskAssigneeUpdateOne) SetNillableApproverID(v *int) *TaskAssigneeUpdateOne {
	if v != nil {
		_u.SetApproverID(*v)
	}
	return _u
}

// ClearApproverID clears the value of the "approver_id" field.
func (_u *TaskAssigneeUpdateOne) ClearApproverID() *TaskAssigneeUpdateOne {
	_u.mutation.ClearApproverID()
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskAssigneeUpdateOne) SetTask(v *Task) *TaskAssigneeUpdateOne {
	return _u.SetTaskID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TaskAssigneeUpdateOne) SetUser(v *User) *TaskAssigneeUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetProposer sets the "proposer" edge to the User entity.
func (_u *TaskAssigneeUpdateOne) SetProposer(v *User) *TaskAssigneeUpdateOne {
	return _u.SetProposerID(v.ID)
}

// SetApprover sets the "approver" edge to the User entity.
func (_u *TaskAssigneeUpdateOne) SetApprover(v *User) *TaskAssigneeUpdateOne {
	return _u.SetApproverID(v.ID)
}

// Mutation returns the TaskAssigneeMutation object of the builder.
func (_u *TaskAssigneeUpdateOne) Mutation() *TaskAssigneeMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskAssigneeUpdateOne) ClearTask() *TaskAssigneeUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TaskAssigneeUpdateOne) ClearUser() *TaskAssigneeUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearProposer clears the "proposer" edge to the User entity.
func (_u *TaskAssigneeUpdateOne) ClearProposer() *TaskAssigneeUpdateOne {
	_u.mutation.ClearProposer()
	return _u
}

// ClearApprover clears the "approver" edge to the User entity.
func (_u *TaskAssigneeUpdateOne) ClearApprover() *TaskAssigneeUpdateOne {
	_u.mutation.ClearApprover()
	return _u
}

// Where appends a list predicates to the TaskAssigneeUpdate builder.
func (_u *TaskAssigneeUpdateOne) Where(ps ...predicate.TaskAssignee) *TaskAssigneeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskAssigneeUpdateOne) Select(field string, fields ...string) *TaskAssigneeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskAssignee entity.
func (_u *TaskAssigneeUpdateOne) Save(ctx context.Context) (*TaskAssignee, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskAssigneeUpdateOne) SaveX(ctx context.Context) *TaskAssignee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskAssigneeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskAssigneeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskAssigneeUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := taskassignee.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TaskAssignee.status": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskAssignee.task"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskAssignee.user"`)
	}
	if _u.mutation.ProposerCleared() && len(_u.mutation.ProposerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskAssignee.proposer"`)
	}
	return nil
}

func (_u *TaskAssigneeUpdateOne) sqlSave(ctx context.Context) (_node *TaskAssignee, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskassignee.Table, taskassignee.Columns, sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskAssignee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskassignee.FieldID)
		for _, f := range fields {
			if !taskassignee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskassignee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(taskassignee.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(taskassignee.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(taskassignee.FieldApprovedAt, field.TypeTime)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProposerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProposerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApproverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApproverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskAssignee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskassignee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
