// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/predicate"
	"asutp-server/ent/taskcategory"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCategoryDelete is the builder for deleting a TaskCategory entity.
type TaskCategoryDelete struct {
	config
	hooks    []Hook
	mutation *TaskCategoryMutation
}

// Where appends a list predicates to the TaskCategoryDelete builder.
func (_d *TaskCategoryDelete) Where(ps ...predicate.TaskCategory) *TaskCategoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TaskCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskCategoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TaskCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(taskcategory.Table, sqlgraph.NewFieldSpec(taskcategory.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TaskCategoryDeleteOne is the builder for deleting a single TaskCategory entity.
type TaskCategoryDeleteOne struct {
	_d *TaskCategoryDelete
}

// Where appends a list predicates to the TaskCategoryDelete builder.
func (_d *TaskCategoryDeleteOne) Where(ps ...predicate.TaskCategory) *TaskCategoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TaskCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taskcategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
