// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/taskassignee"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TaskAssignee is the model entity for the TaskAssignee schema.
type TaskAssignee struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ApprovedAt holds the value of the "approved_at" field.
	ApprovedAt *time.Time `json:"approved_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskAssigneeQuery when eager-loading is set.
	Edges                      TaskAssigneeEdges `json:"edges"`
	task_task_assignees        *int
	user_task_assignee_entries *int
	user_proposed_assignees    *int
	user_approved_assignees    *int
	selectValues               sql.SelectValues
}

// TaskAssigneeEdges holds the relations/edges for other nodes in the graph.
type TaskAssigneeEdges struct {
	// Task holds the value of the task edge.
	Task []*Task `json:"task,omitempty"`
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// Proposer holds the value of the proposer edge.
	Proposer []*User `json:"proposer,omitempty"`
	// Approver holds the value of the approver edge.
	Approver []*User `json:"approver,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading.
func (e TaskAssigneeEdges) TaskOrErr() ([]*Task, error) {
	if e.loadedTypes[0] {
		return e.Task, nil
	}
	return nil, &NotLoadedError{edge: "task"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e TaskAssigneeEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProposerOrErr returns the Proposer value or an error if the edge
// was not loaded in eager-loading.
func (e TaskAssigneeEdges) ProposerOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.Proposer, nil
	}
	return nil, &NotLoadedError{edge: "proposer"}
}

// ApproverOrErr returns the Approver value or an error if the edge
// was not loaded in eager-loading.
func (e TaskAssigneeEdges) ApproverOrErr() ([]*User, error) {
	if e.loadedTypes[3] {
		return e.Approver, nil
	}
	return nil, &NotLoadedError{edge: "approver"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskAssignee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskassignee.FieldID:
			values[i] = new(sql.NullInt64)
		case taskassignee.FieldStatus:
			values[i] = new(sql.NullString)
		case taskassignee.FieldApprovedAt, taskassignee.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case taskassignee.ForeignKeys[0]: // task_task_assignees
			values[i] = new(sql.NullInt64)
		case taskassignee.ForeignKeys[1]: // user_task_assignee_entries
			values[i] = new(sql.NullInt64)
		case taskassignee.ForeignKeys[2]: // user_proposed_assignees
			values[i] = new(sql.NullInt64)
		case taskassignee.ForeignKeys[3]: // user_approved_assignees
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskAssignee fields.
func (_m *TaskAssignee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskassignee.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case taskassignee.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case taskassignee.FieldApprovedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field approved_at", values[i])
			} else if value.Valid {
				_m.ApprovedAt = new(time.Time)
				*_m.ApprovedAt = value.Time
			}
		case taskassignee.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case taskassignee.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field task_task_assignees", value)
			} else if value.Valid {
				_m.task_task_assignees = new(int)
				*_m.task_task_assignees = int(value.Int64)
			}
		case taskassignee.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_task_assignee_entries", value)
			} else if value.Valid {
				_m.user_task_assignee_entries = new(int)
				*_m.user_task_assignee_entries = int(value.Int64)
			}
		case taskassignee.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_proposed_assignees", value)
			} else if value.Valid {
				_m.user_proposed_assignees = new(int)
				*_m.user_proposed_assignees = int(value.Int64)
			}
		case taskassignee.ForeignKeys[3]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_approved_assignees", value)
			} else if value.Valid {
				_m.user_approved_assignees = new(int)
				*_m.user_approved_assignees = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskAssignee.
// This includes values selected through modifiers, order, etc.
func (_m *TaskAssignee) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTask queries the "task" edge of the TaskAssignee entity.
func (_m *TaskAssignee) QueryTask() *TaskQuery {
	return NewTaskAssigneeClient(_m.config).QueryTask(_m)
}

// QueryUser queries the "user" edge of the TaskAssignee entity.
func (_m *TaskAssignee) QueryUser() *UserQuery {
	return NewTaskAssigneeClient(_m.config).QueryUser(_m)
}

// QueryProposer queries the "proposer" edge of the TaskAssignee entity.
func (_m *TaskAssignee) QueryProposer() *UserQuery {
	return NewTaskAssigneeClient(_m.config).QueryProposer(_m)
}

// QueryApprover queries the "approver" edge of the TaskAssignee entity.
func (_m *TaskAssignee) QueryApprover() *UserQuery {
	return NewTaskAssigneeClient(_m.config).QueryApprover(_m)
}

// Update returns a builder for updating this TaskAssignee.
// Note that you need to call TaskAssignee.Unwrap() before calling this method if this TaskAssignee
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskAssignee) Update() *TaskAssigneeUpdateOne {
	return NewTaskAssigneeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskAssignee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskAssignee) Unwrap() *TaskAssignee {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskAssignee is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskAssignee) String() string {
	var builder strings.Builder
	builder.WriteString("TaskAssignee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.ApprovedAt; v != nil {
		builder.WriteString("approved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TaskAssignees is a parsable slice of TaskAssignee.
type TaskAssignees []*TaskAssignee
