// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/predicate"
	"asutp-server/ent/task"
	"asutp-server/ent/taskcategory"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCategoryUpdate is the builder for updating TaskCategory entities.
type TaskCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *TaskCategoryMutation
}

// Where appends a list predicates to the TaskCategoryUpdate builder.
func (_u *TaskCategoryUpdate) Where(ps ...predicate.TaskCategory) *TaskCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TaskCategoryUpdate) SetName(v string) *TaskCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskCategoryUpdate) SetNillableName(v *string) *TaskCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIconIdentifier sets the "icon_identifier" field.
func (_u *TaskCategoryUpdate) SetIconIdentifier(v string) *TaskCategoryUpdate {
	_u.mutation.SetIconIdentifier(v)
	return _u
}

// SetNillableIconIdentifier sets the "icon_identifier" field if the given value is not nil.
func (_u *TaskCategoryUpdate) SetNillableIconIdentifier(v *string) *TaskCategoryUpdate {
	if v != nil {
		_u.SetIconIdentifier(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskCategoryUpdate) SetDescription(v string) *TaskCategoryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskCategoryUpdate) SetNillableDescription(v *string) *TaskCategoryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskCategoryUpdate) ClearDescription() *TaskCategoryUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *TaskCategoryUpdate) AddTaskIDs(ids ...int) *TaskCategoryUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *TaskCategoryUpdate) AddTasks(v ...*Task) *TaskCategoryUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the TaskCategoryMutation object of the builder.
func (_u *TaskCategoryUpdate) Mutation() *TaskCategoryMutation {
	return _u.mutation
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *TaskCategoryUpdate) ClearTasks() *TaskCategoryUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *TaskCategoryUpdate) RemoveTaskIDs(ids ...int) *TaskCategoryUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *TaskCategoryUpdate) RemoveTasks(v ...*Task) *TaskCategoryUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskCategoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskCategoryUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := taskcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TaskCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IconIdentifier(); ok {
		if err := taskcategory.IconIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "icon_identifier", err: fmt.Errorf(`ent: validator failed for field "TaskCategory.icon_identifier": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskcategory.Table, taskcategory.Columns, sqlgraph.NewFieldSpec(taskcategory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(taskcategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconIdentifier(); ok {
		_spec.SetField(taskcategory.FieldIconIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(taskcategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(taskcategory.FieldDescription, field.TypeString)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskcategory.TasksTable,
			Columns: []string{taskcategory.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskcategory.TasksTable,
			Columns: []string{taskcategory.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskcategory.TasksTable,
			Columns: []string{taskcategory.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskCategoryUpdateOne is the builder for updating a single TaskCategory entity.
type TaskCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskCategoryMutation
}

// SetName sets the "name" field.
func (_u *TaskCategoryUpdateOne) SetName(v string) *TaskCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskCategoryUpdateOne) SetNillableName(v *string) *TaskCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIconIdentifier sets the "icon_identifier" field.
func (_u *TaskCategoryUpdateOne) SetIconIdentifier(v string) *TaskCategoryUpdateOne {
	_u.mutation.SetIconIdentifier(v)
	return _u
}

// SetNillableIconIdentifier sets the "icon_identifier" field if the given value is not nil.
func (_u *TaskCategoryUpdateOne) SetNillableIconIdentifier(v *string) *TaskCategoryUpdateOne {
	if v != nil {
		_u.SetIconIdentifier(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskCategoryUpdateOne) SetDescription(v string) *TaskCategoryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskCategoryUpdateOne) SetNillableDescription(v *string) *TaskCategoryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskCategoryUpdateOne) ClearDescription() *TaskCategoryUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *TaskCategoryUpdateOne) AddTaskIDs(ids ...int) *TaskCategoryUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *TaskCategoryUpdateOne) AddTasks(v ...*Task) *TaskCategoryUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the TaskCategoryMutation object of the builder.
func (_u *TaskCategoryUpdateOne) Mutation() *TaskCategoryMutation {
	return _u.mutation
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *TaskCategoryUpdateOne) ClearTasks() *TaskCategoryUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *TaskCategoryUpdateOne) RemoveTaskIDs(ids ...int) *TaskCategoryUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *TaskCategoryUpdateOne) RemoveTasks(v ...*Task) *TaskCategoryUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the TaskCategoryUpdate builder.
func (_u *TaskCategoryUpdateOne) Where(ps ...predicate.TaskCategory) *TaskCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskCategoryUpdateOne) Select(field string, fields ...string) *TaskCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskCategory entity.
func (_u *TaskCategoryUpdateOne) Save(ctx context.Context) (*TaskCategory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskCategoryUpdateOne) SaveX(ctx context.Context) *TaskCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskCategoryUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := taskcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TaskCategory.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IconIdentifier(); ok {
		if err := taskcategory.IconIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "icon_identifier", err: fmt.Errorf(`ent: validator failed for field "TaskCategory.icon_identifier": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskCategoryUpdateOne) sqlSave(ctx context.Context) (_node *TaskCategory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskcategory.Table, taskcategory.Columns, sqlgraph.NewFieldSpec(taskcategory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskcategory.FieldID)
		for _, f := range fields {
			if !taskcategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(taskcategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IconIdentifier(); ok {
		_spec.SetField(taskcategory.FieldIconIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(taskcategory.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(taskcategory.FieldDescription, field.TypeString)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskcategory.TasksTable,
			Columns: []string{taskcategory.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskcategory.TasksTable,
			Columns: []string{taskcategory.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskcategory.TasksTable,
			Columns: []string{taskcategory.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskcategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
