// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/task"
	"asutp-server/ent/taskstatus"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskStatusCreate is the builder for creating a TaskStatus entity.
type TaskStatusCreate struct {
	config
	mutation *TaskStatusMutation
	hooks    []Hook
}

// SetCode sets the "code" field.
func (_c *TaskStatusCreate) SetCode(v string) *TaskStatusCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetIsTerminal sets the "is_terminal" field.
func (_c *TaskStatusCreate) SetIsTerminal(v bool) *TaskStatusCreate {
	_c.mutation.SetIsTerminal(v)
	return _c
}

// SetNillableIsTerminal sets the "is_terminal" field if the given value is not nil.
func (_c *TaskStatusCreate) SetNillableIsTerminal(v *bool) *TaskStatusCreate {
	if v != nil {
		_c.SetIsTerminal(*v)
	}
	return _c
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_c *TaskStatusCreate) AddTaskIDs(ids ...int) *TaskStatusCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_c *TaskStatusCreate) AddTasks(v ...*Task) *TaskStatusCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// Mutation returns the TaskStatusMutation object of the builder.
func (_c *TaskStatusCreate) Mutation() *TaskStatusMutation {
	return _c.mutation
}

// Save creates the TaskStatus in the database.
func (_c *TaskStatusCreate) Save(ctx context.Context) (*TaskStatus, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskStatusCreate) SaveX(ctx context.Context) *TaskStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskStatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskStatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskStatusCreate) defaults() {
	if _, ok := _c.mutation.IsTerminal(); !ok {
		v := taskstatus.DefaultIsTerminal
		_c.mutation.SetIsTerminal(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskStatusCreate) check() error {
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "TaskStatus.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := taskstatus.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TaskStatus.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsTerminal(); !ok {
		return &ValidationError{Name: "is_terminal", err: errors.New(`ent: missing required field "TaskStatus.is_terminal"`)}
	}
	return nil
}

func (_c *TaskStatusCreate) sqlSave(ctx context.Context) (*TaskStatus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskStatusCreate) createSpec() (*TaskStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskStatus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskstatus.Table, sqlgraph.NewFieldSpec(taskstatus.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(taskstatus.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.IsTerminal(); ok {
		_spec.SetField(taskstatus.FieldIsTerminal, field.TypeBool, value)
		_node.IsTerminal = value
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskstatus.TasksTable,
			Columns: []string{taskstatus.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskStatusCreateBulk is the builder for creating many TaskStatus entities in bulk.
type TaskStatusCreateBulk struct {
	config
	err      error
	builders []*TaskStatusCreate
}

// Save creates the TaskStatus entities in the database.
func (_c *TaskStatusCreateBulk) Save(ctx context.Context) ([]*TaskStatus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskStatus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskStatusCreateBulk) SaveX(ctx context.Context) []*TaskStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskStatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
