// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/priority"
	"asutp-server/ent/task"
	"asutp-server/ent/taskcategory"
	"asutp-server/ent/taskstatus"
	"asutp-server/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Task is the model entity for the Task schema.
type Task struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// DueDate holds the value of the "due_date" field.
	DueDate time.Time `json:"due_date,omitempty"`
	// PriorityID holds the value of the "priority_id" field.
	PriorityID int `json:"priority_id,omitempty"`
	// StatusID holds the value of the "status_id" field.
	StatusID int `json:"status_id,omitempty"`
	// CategoryID holds the value of the "category_id" field.
	CategoryID *int `json:"category_id,omitempty"`
	// Progress holds the value of the "progress" field.
	Progress int16 `json:"progress,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int `json:"created_by,omitempty"`
	// AssignedTo holds the value of the "assigned_to" field.
	AssignedTo *int `json:"assigned_to,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskQuery when eager-loading is set.
	Edges              TaskEdges `json:"edges"`
	task_assignee_task *int
	selectValues       sql.SelectValues
}

// TaskEdges holds the relations/edges for other nodes in the graph.
type TaskEdges struct {
	// Priority holds the value of the priority edge.
	Priority *Priority `json:"priority,omitempty"`
	// Status holds the value of the status edge.
	Status *TaskStatus `json:"status,omitempty"`
	// Category holds the value of the category edge.
	Category *TaskCategory `json:"category,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Assignee holds the value of the assignee edge.
	Assignee *User `json:"assignee,omitempty"`
	// TaskAssignees holds the value of the task_assignees edge.
	TaskAssignees []*TaskAssignee `json:"task_assignees,omitempty"`
	// Histories holds the value of the histories edge.
	Histories []*TaskHistory `json:"histories,omitempty"`
	// Notifications holds the value of the notifications edge.
	Notifications []*Notification `json:"notifications,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// PriorityOrErr returns the Priority value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) PriorityOrErr() (*Priority, error) {
	if e.Priority != nil {
		return e.Priority, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: priority.Label}
	}
	return nil, &NotLoadedError{edge: "priority"}
}

// StatusOrErr returns the Status value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) StatusOrErr() (*TaskStatus, error) {
	if e.Status != nil {
		return e.Status, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: taskstatus.Label}
	}
	return nil, &NotLoadedError{edge: "status"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) CategoryOrErr() (*TaskCategory, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: taskcategory.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// AssigneeOrErr returns the Assignee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TaskEdges) AssigneeOrErr() (*User, error) {
	if e.Assignee != nil {
		return e.Assignee, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "assignee"}
}

// TaskAssigneesOrErr returns the TaskAssignees value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) TaskAssigneesOrErr() ([]*TaskAssignee, error) {
	if e.loadedTypes[5] {
		return e.TaskAssignees, nil
	}
	return nil, &NotLoadedError{edge: "task_assignees"}
}

// HistoriesOrErr returns the Histories value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) HistoriesOrErr() ([]*TaskHistory, error) {
	if e.loadedTypes[6] {
		return e.Histories, nil
	}
	return nil, &NotLoadedError{edge: "histories"}
}

// NotificationsOrErr returns the Notifications value or an error if the edge
// was not loaded in eager-loading.
func (e TaskEdges) NotificationsOrErr() ([]*Notification, error) {
	if e.loadedTypes[7] {
		return e.Notifications, nil
	}
	return nil, &NotLoadedError{edge: "notifications"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldID, task.FieldPriorityID, task.FieldStatusID, task.FieldCategoryID, task.FieldProgress, task.FieldCreatedBy, task.FieldAssignedTo:
			values[i] = new(sql.NullInt64)
		case task.FieldTitle, task.FieldDescription:
			values[i] = new(sql.NullString)
		case task.FieldDueDate, task.FieldCreatedAt, task.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case task.ForeignKeys[0]: // task_assignee_task
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (_m *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case task.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case task.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case task.FieldDueDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field due_date", values[i])
			} else if value.Valid {
				_m.DueDate = value.Time
			}
		case task.FieldPriorityID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority_id", values[i])
			} else if value.Valid {
				_m.PriorityID = int(value.Int64)
			}
		case task.FieldStatusID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_id", values[i])
			} else if value.Valid {
				_m.StatusID = int(value.Int64)
			}
		case task.FieldCategoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field category_id", values[i])
			} else if value.Valid {
				_m.CategoryID = new(int)
				*_m.CategoryID = int(value.Int64)
			}
		case task.FieldProgress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = int16(value.Int64)
			}
		case task.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = int(value.Int64)
			}
		case task.FieldAssignedTo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_to", values[i])
			} else if value.Valid {
				_m.AssignedTo = new(int)
				*_m.AssignedTo = int(value.Int64)
			}
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case task.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case task.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field task_assignee_task", value)
			} else if value.Valid {
				_m.task_assignee_task = new(int)
				*_m.task_assignee_task = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (_m *Task) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPriority queries the "priority" edge of the Task entity.
func (_m *Task) QueryPriority() *PriorityQuery {
	return NewTaskClient(_m.config).QueryPriority(_m)
}

// QueryStatus queries the "status" edge of the Task entity.
func (_m *Task) QueryStatus() *TaskStatusQuery {
	return NewTaskClient(_m.config).QueryStatus(_m)
}

// QueryCategory queries the "category" edge of the Task entity.
func (_m *Task) QueryCategory() *TaskCategoryQuery {
	return NewTaskClient(_m.config).QueryCategory(_m)
}

// QueryCreator queries the "creator" edge of the Task entity.
func (_m *Task) QueryCreator() *UserQuery {
	return NewTaskClient(_m.config).QueryCreator(_m)
}

// QueryAssignee queries the "assignee" edge of the Task entity.
func (_m *Task) QueryAssignee() *UserQuery {
	return NewTaskClient(_m.config).QueryAssignee(_m)
}

// QueryTaskAssignees queries the "task_assignees" edge of the Task entity.
func (_m *Task) QueryTaskAssignees() *TaskAssigneeQuery {
	return NewTaskClient(_m.config).QueryTaskAssignees(_m)
}

// QueryHistories queries the "histories" edge of the Task entity.
func (_m *Task) QueryHistories() *TaskHistoryQuery {
	return NewTaskClient(_m.config).QueryHistories(_m)
}

// QueryNotifications queries the "notifications" edge of the Task entity.
func (_m *Task) QueryNotifications() *NotificationQuery {
	return NewTaskClient(_m.config).QueryNotifications(_m)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Task) Update() *TaskUpdateOne {
	return NewTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Task) Unwrap() *Task {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("due_date=")
	builder.WriteString(_m.DueDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("priority_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriorityID))
	builder.WriteString(", ")
	builder.WriteString("status_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusID))
	builder.WriteString(", ")
	if v := _m.CategoryID; v != nil {
		builder.WriteString("category_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Progress))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	if v := _m.AssignedTo; v != nil {
		builder.WriteString("assigned_to=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
