// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/predicate"
	"asutp-server/ent/task"
	"asutp-server/ent/taskassignee"
	"asutp-server/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskAssigneeUpdate is the builder for updating TaskAssignee entities.
type TaskAssigneeUpdate struct {
	config
	hooks    []Hook
	mutation *TaskAssigneeMutation
}

// Where appends a list predicates to the TaskAssigneeUpdate builder.
func (_u *TaskAssigneeUpdate) Where(ps ...predicate.TaskAssignee) *TaskAssigneeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskAssigneeUpdate) SetStatus(v string) *TaskAssigneeUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskAssigneeUpdate) SetNillableStatus(v *string) *TaskAssigneeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *TaskAssigneeUpdate) SetApprovedAt(v time.Time) *TaskAssigneeUpdate {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *TaskAssigneeUpdate) SetNillableApprovedAt(v *time.Time) *TaskAssigneeUpdate {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *TaskAssigneeUpdate) ClearApprovedAt() *TaskAssigneeUpdate {
	_u.mutation.ClearApprovedAt()
	return _u
}

// AddTaskIDs adds the "task" edge to the Task entity by IDs.
func (_u *TaskAssigneeUpdate) AddTaskIDs(ids ...int) *TaskAssigneeUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTask adds the "task" edges to the Task entity.
func (_u *TaskAssigneeUpdate) AddTask(v ...*Task) *TaskAssigneeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *TaskAssigneeUpdate) AddUserIDs(ids ...int) *TaskAssigneeUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *TaskAssigneeUpdate) AddUser(v ...*User) *TaskAssigneeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddProposerIDs adds the "proposer" edge to the User entity by IDs.
func (_u *TaskAssigneeUpdate) AddProposerIDs(ids ...int) *TaskAssigneeUpdate {
	_u.mutation.AddProposerIDs(ids...)
	return _u
}

// AddProposer adds the "proposer" edges to the User entity.
func (_u *TaskAssigneeUpdate) AddProposer(v ...*User) *TaskAssigneeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProposerIDs(ids...)
}

// AddApproverIDs adds the "approver" edge to the User entity by IDs.
func (_u *TaskAssigneeUpdate) AddApproverIDs(ids ...int) *TaskAssigneeUpdate {
	_u.mutation.AddApproverIDs(ids...)
	return _u
}

// AddApprover adds the "approver" edges to the User entity.
func (_u *TaskAssigneeUpdate) AddApprover(v ...*User) *TaskAssigneeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddApproverIDs(ids...)
}

// Mutation returns the TaskAssigneeMutation object of the builder.
func (_u *TaskAssigneeUpdate) Mutation() *TaskAssigneeMutation {
	return _u.mutation
}

// ClearTask clears all "task" edges to the Task entity.
func (_u *TaskAssigneeUpdate) ClearTask() *TaskAssigneeUpdate {
	_u.mutation.ClearTask()
	return _u
}

// RemoveTaskIDs removes the "task" edge to Task entities by IDs.
func (_u *TaskAssigneeUpdate) RemoveTaskIDs(ids ...int) *TaskAssigneeUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTask removes "task" edges to Task entities.
func (_u *TaskAssigneeUpdate) RemoveTask(v ...*Task) *TaskAssigneeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// ClearUser clears all "user" edges to the User entity.
func (_u *TaskAssigneeUpdate) ClearUser() *TaskAssigneeUpdate {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *TaskAssigneeUpdate) RemoveUserIDs(ids ...int) *TaskAssigneeUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *TaskAssigneeUpdate) RemoveUser(v ...*User) *TaskAssigneeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearProposer clears all "proposer" edges to the User entity.
func (_u *TaskAssigneeUpdate) ClearProposer() *TaskAssigneeUpdate {
	_u.mutation.ClearProposer()
	return _u
}

// RemoveProposerIDs removes the "proposer" edge to User entities by IDs.
func (_u *TaskAssigneeUpdate) RemoveProposerIDs(ids ...int) *TaskAssigneeUpdate {
	_u.mutation.RemoveProposerIDs(ids...)
	return _u
}

// RemoveProposer removes "proposer" edges to User entities.
func (_u *TaskAssigneeUpdate) RemoveProposer(v ...*User) *TaskAssigneeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProposerIDs(ids...)
}

// ClearApprover clears all "approver" edges to the User entity.
func (_u *TaskAssigneeUpdate) ClearApprover() *TaskAssigneeUpdate {
	_u.mutation.ClearApprover()
	return _u
}

// RemoveApproverIDs removes the "approver" edge to User entities by IDs.
func (_u *TaskAssigneeUpdate) RemoveApproverIDs(ids ...int) *TaskAssigneeUpdate {
	_u.mutation.RemoveApproverIDs(ids...)
	return _u
}

// RemoveApprover removes "approver" edges to User entities.
func (_u *TaskAssigneeUpdate) RemoveApprover(v ...*User) *TaskAssigneeUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveApproverIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskAssigneeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskAssigneeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskAssigneeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskAssigneeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskAssigneeUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := taskassignee.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TaskAssignee.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskAssigneeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskassignee.Table, taskassignee.Columns, sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(taskassignee.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(taskassignee.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(taskassignee.FieldApprovedAt, field.TypeTime)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskIDs(); len(nodes) > 0 && !_u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProposerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProposerIDs(); len(nodes) > 0 && !_u.mutation.ProposerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProposerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApproverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedApproverIDs(); len(nodes) > 0 && !_u.mutation.ApproverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApproverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskassignee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskAssigneeUpdateOne is the builder for updating a single TaskAssignee entity.
type TaskAssigneeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskAssigneeMutation
}

// SetStatus sets the "status" field.
func (_u *TaskAssigneeUpdateOne) SetStatus(v string) *TaskAssigneeUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskAssigneeUpdateOne) SetNillableStatus(v *string) *TaskAssigneeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *TaskAssigneeUpdateOne) SetApprovedAt(v time.Time) *TaskAssigneeUpdateOne {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *TaskAssigneeUpdateOne) SetNillableApprovedAt(v *time.Time) *TaskAssigneeUpdateOne {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *TaskAssigneeUpdateOne) ClearApprovedAt() *TaskAssigneeUpdateOne {
	_u.mutation.ClearApprovedAt()
	return _u
}

// AddTaskIDs adds the "task" edge to the Task entity by IDs.
func (_u *TaskAssigneeUpdateOne) AddTaskIDs(ids ...int) *TaskAssigneeUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTask adds the "task" edges to the Task entity.
func (_u *TaskAssigneeUpdateOne) AddTask(v ...*Task) *TaskAssigneeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *TaskAssigneeUpdateOne) AddUserIDs(ids ...int) *TaskAssigneeUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *TaskAssigneeUpdateOne) AddUser(v ...*User) *TaskAssigneeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// AddProposerIDs adds the "proposer" edge to the User entity by IDs.
func (_u *TaskAssigneeUpdateOne) AddProposerIDs(ids ...int) *TaskAssigneeUpdateOne {
	_u.mutation.AddProposerIDs(ids...)
	return _u
}

// AddProposer adds the "proposer" edges to the User entity.
func (_u *TaskAssigneeUpdateOne) AddProposer(v ...*User) *TaskAssigneeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProposerIDs(ids...)
}

// AddApproverIDs adds the "approver" edge to the User entity by IDs.
func (_u *TaskAssigneeUpdateOne) AddApproverIDs(ids ...int) *TaskAssigneeUpdateOne {
	_u.mutation.AddApproverIDs(ids...)
	return _u
}

// AddApprover adds the "approver" edges to the User entity.
func (_u *TaskAssigneeUpdateOne) AddApprover(v ...*User) *TaskAssigneeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddApproverIDs(ids...)
}

// Mutation returns the TaskAssigneeMutation object of the builder.
func (_u *TaskAssigneeUpdateOne) Mutation() *TaskAssigneeMutation {
	return _u.mutation
}

// ClearTask clears all "task" edges to the Task entity.
func (_u *TaskAssigneeUpdateOne) ClearTask() *TaskAssigneeUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// RemoveTaskIDs removes the "task" edge to Task entities by IDs.
func (_u *TaskAssigneeUpdateOne) RemoveTaskIDs(ids ...int) *TaskAssigneeUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTask removes "task" edges to Task entities.
func (_u *TaskAssigneeUpdateOne) RemoveTask(v ...*Task) *TaskAssigneeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// ClearUser clears all "user" edges to the User entity.
func (_u *TaskAssigneeUpdateOne) ClearUser() *TaskAssigneeUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *TaskAssigneeUpdateOne) RemoveUserIDs(ids ...int) *TaskAssigneeUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *TaskAssigneeUpdateOne) RemoveUser(v ...*User) *TaskAssigneeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// ClearProposer clears all "proposer" edges to the User entity.
func (_u *TaskAssigneeUpdateOne) ClearProposer() *TaskAssigneeUpdateOne {
	_u.mutation.ClearProposer()
	return _u
}

// RemoveProposerIDs removes the "proposer" edge to User entities by IDs.
func (_u *TaskAssigneeUpdateOne) RemoveProposerIDs(ids ...int) *TaskAssigneeUpdateOne {
	_u.mutation.RemoveProposerIDs(ids...)
	return _u
}

// RemoveProposer removes "proposer" edges to User entities.
func (_u *TaskAssigneeUpdateOne) RemoveProposer(v ...*User) *TaskAssigneeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProposerIDs(ids...)
}

// ClearApprover clears all "approver" edges to the User entity.
func (_u *TaskAssigneeUpdateOne) ClearApprover() *TaskAssigneeUpdateOne {
	_u.mutation.ClearApprover()
	return _u
}

// RemoveApproverIDs removes the "approver" edge to User entities by IDs.
func (_u *TaskAssigneeUpdateOne) RemoveApproverIDs(ids ...int) *TaskAssigneeUpdateOne {
	_u.mutation.RemoveApproverIDs(ids...)
	return _u
}

// RemoveApprover removes "approver" edges to User entities.
func (_u *TaskAssigneeUpdateOne) RemoveApprover(v ...*User) *TaskAssigneeUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveApproverIDs(ids...)
}

// Where appends a list predicates to the TaskAssigneeUpdate builder.
func (_u *TaskAssigneeUpdateOne) Where(ps ...predicate.TaskAssignee) *TaskAssigneeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskAssigneeUpdateOne) Select(field string, fields ...string) *TaskAssigneeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskAssignee entity.
func (_u *TaskAssigneeUpdateOne) Save(ctx context.Context) (*TaskAssignee, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskAssigneeUpdateOne) SaveX(ctx context.Context) *TaskAssignee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskAssigneeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskAssigneeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskAssigneeUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := taskassignee.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TaskAssignee.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskAssigneeUpdateOne) sqlSave(ctx context.Context) (_node *TaskAssignee, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskassignee.Table, taskassignee.Columns, sqlgraph.NewFieldSpec(taskassignee.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskAssignee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskassignee.FieldID)
		for _, f := range fields {
			if !taskassignee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskassignee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(taskassignee.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(taskassignee.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(taskassignee.FieldApprovedAt, field.TypeTime)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTaskIDs(); len(nodes) > 0 && !_u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.TaskTable,
			Columns: []string{taskassignee.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.UserTable,
			Columns: []string{taskassignee.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProposerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProposerIDs(); len(nodes) > 0 && !_u.mutation.ProposerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProposerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ProposerTable,
			Columns: []string{taskassignee.ProposerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApproverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedApproverIDs(); len(nodes) > 0 && !_u.mutation.ApproverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApproverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskassignee.ApproverTable,
			Columns: []string{taskassignee.ApproverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskAssignee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskassignee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
