// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/predicate"
	"asutp-server/ent/task"
	"asutp-server/ent/taskstatus"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskStatusUpdate is the builder for updating TaskStatus entities.
type TaskStatusUpdate struct {
	config
	hooks    []Hook
	mutation *TaskStatusMutation
}

// Where appends a list predicates to the TaskStatusUpdate builder.
func (_u *TaskStatusUpdate) Where(ps ...predicate.TaskStatus) *TaskStatusUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *TaskStatusUpdate) SetCode(v string) *TaskStatusUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TaskStatusUpdate) SetNillableCode(v *string) *TaskStatusUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetIsTerminal sets the "is_terminal" field.
func (_u *TaskStatusUpdate) SetIsTerminal(v bool) *TaskStatusUpdate {
	_u.mutation.SetIsTerminal(v)
	return _u
}

// SetNillableIsTerminal sets the "is_terminal" field if the given value is not nil.
func (_u *TaskStatusUpdate) SetNillableIsTerminal(v *bool) *TaskStatusUpdate {
	if v != nil {
		_u.SetIsTerminal(*v)
	}
	return _u
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *TaskStatusUpdate) AddTaskIDs(ids ...int) *TaskStatusUpdate {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *TaskStatusUpdate) AddTasks(v ...*Task) *TaskStatusUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the TaskStatusMutation object of the builder.
func (_u *TaskStatusUpdate) Mutation() *TaskStatusMutation {
	return _u.mutation
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *TaskStatusUpdate) ClearTasks() *TaskStatusUpdate {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *TaskStatusUpdate) RemoveTaskIDs(ids ...int) *TaskStatusUpdate {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *TaskStatusUpdate) RemoveTasks(v ...*Task) *TaskStatusUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskStatusUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskStatusUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskStatusUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskStatusUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := taskstatus.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TaskStatus.code": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskStatusUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskstatus.Table, taskstatus.Columns, sqlgraph.NewFieldSpec(taskstatus.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(taskstatus.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsTerminal(); ok {
		_spec.SetField(taskstatus.FieldIsTerminal, field.TypeBool, value)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskstatus.TasksTable,
			Columns: []string{taskstatus.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskstatus.TasksTable,
			Columns: []string{taskstatus.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskstatus.TasksTable,
			Columns: []string{taskstatus.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskStatusUpdateOne is the builder for updating a single TaskStatus entity.
type TaskStatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskStatusMutation
}

// SetCode sets the "code" field.
func (_u *TaskStatusUpdateOne) SetCode(v string) *TaskStatusUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TaskStatusUpdateOne) SetNillableCode(v *string) *TaskStatusUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetIsTerminal sets the "is_terminal" field.
func (_u *TaskStatusUpdateOne) SetIsTerminal(v bool) *TaskStatusUpdateOne {
	_u.mutation.SetIsTerminal(v)
	return _u
}

// SetNillableIsTerminal sets the "is_terminal" field if the given value is not nil.
func (_u *TaskStatusUpdateOne) SetNillableIsTerminal(v *bool) *TaskStatusUpdateOne {
	if v != nil {
		_u.SetIsTerminal(*v)
	}
	return _u
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_u *TaskStatusUpdateOne) AddTaskIDs(ids ...int) *TaskStatusUpdateOne {
	_u.mutation.AddTaskIDs(ids...)
	return _u
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_u *TaskStatusUpdateOne) AddTasks(v ...*Task) *TaskStatusUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTaskIDs(ids...)
}

// Mutation returns the TaskStatusMutation object of the builder.
func (_u *TaskStatusUpdateOne) Mutation() *TaskStatusMutation {
	return _u.mutation
}

// ClearTasks clears all "tasks" edges to the Task entity.
func (_u *TaskStatusUpdateOne) ClearTasks() *TaskStatusUpdateOne {
	_u.mutation.ClearTasks()
	return _u
}

// RemoveTaskIDs removes the "tasks" edge to Task entities by IDs.
func (_u *TaskStatusUpdateOne) RemoveTaskIDs(ids ...int) *TaskStatusUpdateOne {
	_u.mutation.RemoveTaskIDs(ids...)
	return _u
}

// RemoveTasks removes "tasks" edges to Task entities.
func (_u *TaskStatusUpdateOne) RemoveTasks(v ...*Task) *TaskStatusUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTaskIDs(ids...)
}

// Where appends a list predicates to the TaskStatusUpdate builder.
func (_u *TaskStatusUpdateOne) Where(ps ...predicate.TaskStatus) *TaskStatusUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskStatusUpdateOne) Select(field string, fields ...string) *TaskStatusUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskStatus entity.
func (_u *TaskStatusUpdateOne) Save(ctx context.Context) (*TaskStatus, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskStatusUpdateOne) SaveX(ctx context.Context) *TaskStatus {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskStatusUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskStatusUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := taskstatus.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "TaskStatus.code": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskStatusUpdateOne) sqlSave(ctx context.Context) (_node *TaskStatus, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskstatus.Table, taskstatus.Columns, sqlgraph.NewFieldSpec(taskstatus.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskStatus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskstatus.FieldID)
		for _, f := range fields {
			if !taskstatus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskstatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(taskstatus.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsTerminal(); ok {
		_spec.SetField(taskstatus.FieldIsTerminal, field.TypeBool, value)
	}
	if _u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskstatus.TasksTable,
			Columns: []string{taskstatus.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTasksIDs(); len(nodes) > 0 && !_u.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskstatus.TasksTable,
			Columns: []string{taskstatus.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskstatus.TasksTable,
			Columns: []string{taskstatus.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskStatus{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
