// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/task"
	"asutp-server/ent/taskcategory"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskCategoryCreate is the builder for creating a TaskCategory entity.
type TaskCategoryCreate struct {
	config
	mutation *TaskCategoryMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TaskCategoryCreate) SetName(v string) *TaskCategoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIconIdentifier sets the "icon_identifier" field.
func (_c *TaskCategoryCreate) SetIconIdentifier(v string) *TaskCategoryCreate {
	_c.mutation.SetIconIdentifier(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TaskCategoryCreate) SetDescription(v string) *TaskCategoryCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TaskCategoryCreate) SetNillableDescription(v *string) *TaskCategoryCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *TaskCategoryCreate) SetIsActive(v bool) *TaskCategoryCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *TaskCategoryCreate) SetNillableIsActive(v *bool) *TaskCategoryCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (_c *TaskCategoryCreate) AddTaskIDs(ids ...int) *TaskCategoryCreate {
	_c.mutation.AddTaskIDs(ids...)
	return _c
}

// AddTasks adds the "tasks" edges to the Task entity.
func (_c *TaskCategoryCreate) AddTasks(v ...*Task) *TaskCategoryCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTaskIDs(ids...)
}

// Mutation returns the TaskCategoryMutation object of the builder.
func (_c *TaskCategoryCreate) Mutation() *TaskCategoryMutation {
	return _c.mutation
}

// Save creates the TaskCategory in the database.
func (_c *TaskCategoryCreate) Save(ctx context.Context) (*TaskCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskCategoryCreate) SaveX(ctx context.Context) *TaskCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskCategoryCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := taskcategory.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskCategoryCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TaskCategory.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := taskcategory.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TaskCategory.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IconIdentifier(); !ok {
		return &ValidationError{Name: "icon_identifier", err: errors.New(`ent: missing required field "TaskCategory.icon_identifier"`)}
	}
	if v, ok := _c.mutation.IconIdentifier(); ok {
		if err := taskcategory.IconIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "icon_identifier", err: fmt.Errorf(`ent: validator failed for field "TaskCategory.icon_identifier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "TaskCategory.is_active"`)}
	}
	return nil
}

func (_c *TaskCategoryCreate) sqlSave(ctx context.Context) (*TaskCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskCategoryCreate) createSpec() (*TaskCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskcategory.Table, sqlgraph.NewFieldSpec(taskcategory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(taskcategory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IconIdentifier(); ok {
		_spec.SetField(taskcategory.FieldIconIdentifier, field.TypeString, value)
		_node.IconIdentifier = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(taskcategory.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(taskcategory.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := _c.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taskcategory.TasksTable,
			Columns: []string{taskcategory.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskCategoryCreateBulk is the builder for creating many TaskCategory entities in bulk.
type TaskCategoryCreateBulk struct {
	config
	err      error
	builders []*TaskCategoryCreate
}

// Save creates the TaskCategory entities in the database.
func (_c *TaskCategoryCreateBulk) Save(ctx context.Context) ([]*TaskCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskCategoryCreateBulk) SaveX(ctx context.Context) []*TaskCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
