// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/changetype"
	"asutp-server/ent/predicate"
	"asutp-server/ent/task"
	"asutp-server/ent/taskhistory"
	"asutp-server/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskHistoryUpdate is the builder for updating TaskHistory entities.
type TaskHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *TaskHistoryMutation
}

// Where appends a list predicates to the TaskHistoryUpdate builder.
func (_u *TaskHistoryUpdate) Where(ps ...predicate.TaskHistory) *TaskHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *TaskHistoryUpdate) SetTaskID(v int) *TaskHistoryUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableTaskID(v *int) *TaskHistoryUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetChangedBy sets the "changed_by" field.
func (_u *TaskHistoryUpdate) SetChangedBy(v int) *TaskHistoryUpdate {
	_u.mutation.SetChangedBy(v)
	return _u
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableChangedBy(v *int) *TaskHistoryUpdate {
	if v != nil {
		_u.SetChangedBy(*v)
	}
	return _u
}

// SetChangeTypeID sets the "change_type_id" field.
func (_u *TaskHistoryUpdate) SetChangeTypeID(v int) *TaskHistoryUpdate {
	_u.mutation.SetChangeTypeID(v)
	return _u
}

// SetNillableChangeTypeID sets the "change_type_id" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableChangeTypeID(v *int) *TaskHistoryUpdate {
	if v != nil {
		_u.SetChangeTypeID(*v)
	}
	return _u
}

// SetFieldName sets the "field_name" field.
func (_u *TaskHistoryUpdate) SetFieldName(v string) *TaskHistoryUpdate {
	_u.mutation.SetFieldName(v)
	return _u
}

// SetNillableFieldName sets the "field_name" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableFieldName(v *string) *TaskHistoryUpdate {
	if v != nil {
		_u.SetFieldName(*v)
	}
	return _u
}

// ClearFieldName clears the value of the "field_name" field.
func (_u *TaskHistoryUpdate) ClearFieldName() *TaskHistoryUpdate {
	_u.mutation.ClearFieldName()
	return _u
}

// SetOldValue sets the "old_value" field.
func (_u *TaskHistoryUpdate) SetOldValue(v string) *TaskHistoryUpdate {
	_u.mutation.SetOldValue(v)
	return _u
}

// SetNillableOldValue sets the "old_value" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableOldValue(v *string) *TaskHistoryUpdate {
	if v != nil {
		_u.SetOldValue(*v)
	}
	return _u
}

// ClearOldValue clears the value of the "old_value" field.
func (_u *TaskHistoryUpdate) ClearOldValue() *TaskHistoryUpdate {
	_u.mutation.ClearOldValue()
	return _u
}

// SetNewValue sets the "new_value" field.
func (_u *TaskHistoryUpdate) SetNewValue(v string) *TaskHistoryUpdate {
	_u.mutation.SetNewValue(v)
	return _u
}

// SetNillableNewValue sets the "new_value" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableNewValue(v *string) *TaskHistoryUpdate {
	if v != nil {
		_u.SetNewValue(*v)
	}
	return _u
}

// ClearNewValue clears the value of the "new_value" field.
func (_u *TaskHistoryUpdate) ClearNewValue() *TaskHistoryUpdate {
	_u.mutation.ClearNewValue()
	return _u
}

// SetDisplayText sets the "display_text" field.
func (_u *TaskHistoryUpdate) SetDisplayText(v string) *TaskHistoryUpdate {
	_u.mutation.SetDisplayText(v)
	return _u
}

// SetNillableDisplayText sets the "display_text" field if the given value is not nil.
func (_u *TaskHistoryUpdate) SetNillableDisplayText(v *string) *TaskHistoryUpdate {
	if v != nil {
		_u.SetDisplayText(*v)
	}
	return _u
}

// ClearDisplayText clears the value of the "display_text" field.
func (_u *TaskHistoryUpdate) ClearDisplayText() *TaskHistoryUpdate {
	_u.mutation.ClearDisplayText()
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskHistoryUpdate) SetTask(v *Task) *TaskHistoryUpdate {
	return _u.SetTaskID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *TaskHistoryUpdate) SetUserID(id int) *TaskHistoryUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TaskHistoryUpdate) SetUser(v *User) *TaskHistoryUpdate {
	return _u.SetUserID(v.ID)
}

// SetChangeType sets the "change_type" edge to the ChangeType entity.
func (_u *TaskHistoryUpdate) SetChangeType(v *ChangeType) *TaskHistoryUpdate {
	return _u.SetChangeTypeID(v.ID)
}

// Mutation returns the TaskHistoryMutation object of the builder.
func (_u *TaskHistoryUpdate) Mutation() *TaskHistoryMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskHistoryUpdate) ClearTask() *TaskHistoryUpdate {
	_u.mutation.ClearTask()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TaskHistoryUpdate) ClearUser() *TaskHistoryUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearChangeType clears the "change_type" edge to the ChangeType entity.
func (_u *TaskHistoryUpdate) ClearChangeType() *TaskHistoryUpdate {
	_u.mutation.ClearChangeType()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskHistoryUpdate) check() error {
	if v, ok := _u.mutation.FieldName(); ok {
		if err := taskhistory.FieldNameValidator(v); err != nil {
			return &ValidationError{Name: "field_name", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.field_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayText(); ok {
		if err := taskhistory.DisplayTextValidator(v); err != nil {
			return &ValidationError{Name: "display_text", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.display_text": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskHistory.task"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskHistory.user"`)
	}
	if _u.mutation.ChangeTypeCleared() && len(_u.mutation.ChangeTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskHistory.change_type"`)
	}
	return nil
}

func (_u *TaskHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskhistory.Table, taskhistory.Columns, sqlgraph.NewFieldSpec(taskhistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FieldName(); ok {
		_spec.SetField(taskhistory.FieldFieldName, field.TypeString, value)
	}
	if _u.mutation.FieldNameCleared() {
		_spec.ClearField(taskhistory.FieldFieldName, field.TypeString)
	}
	if value, ok := _u.mutation.OldValue(); ok {
		_spec.SetField(taskhistory.FieldOldValue, field.TypeString, value)
	}
	if _u.mutation.OldValueCleared() {
		_spec.ClearField(taskhistory.FieldOldValue, field.TypeString)
	}
	if value, ok := _u.mutation.NewValue(); ok {
		_spec.SetField(taskhistory.FieldNewValue, field.TypeString, value)
	}
	if _u.mutation.NewValueCleared() {
		_spec.ClearField(taskhistory.FieldNewValue, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayText(); ok {
		_spec.SetField(taskhistory.FieldDisplayText, field.TypeString, value)
	}
	if _u.mutation.DisplayTextCleared() {
		_spec.ClearField(taskhistory.FieldDisplayText, field.TypeString)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.UserTable,
			Columns: []string{taskhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.UserTable,
			Columns: []string{taskhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangeTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.ChangeTypeTable,
			Columns: []string{taskhistory.ChangeTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changetype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.ChangeTypeTable,
			Columns: []string{taskhistory.ChangeTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changetype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskHistoryUpdateOne is the builder for updating a single TaskHistory entity.
type TaskHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskHistoryMutation
}

// SetTaskID sets the "task_id" field.
func (_u *TaskHistoryUpdateOne) SetTaskID(v int) *TaskHistoryUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableTaskID(v *int) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetChangedBy sets the "changed_by" field.
func (_u *TaskHistoryUpdateOne) SetChangedBy(v int) *TaskHistoryUpdateOne {
	_u.mutation.SetChangedBy(v)
	return _u
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableChangedBy(v *int) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetChangedBy(*v)
	}
	return _u
}

// SetChangeTypeID sets the "change_type_id" field.
func (_u *TaskHistoryUpdateOne) SetChangeTypeID(v int) *TaskHistoryUpdateOne {
	_u.mutation.SetChangeTypeID(v)
	return _u
}

// SetNillableChangeTypeID sets the "change_type_id" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableChangeTypeID(v *int) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetChangeTypeID(*v)
	}
	return _u
}

// SetFieldName sets the "field_name" field.
func (_u *TaskHistoryUpdateOne) SetFieldName(v string) *TaskHistoryUpdateOne {
	_u.mutation.SetFieldName(v)
	return _u
}

// SetNillableFieldName sets the "field_name" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableFieldName(v *string) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetFieldName(*v)
	}
	return _u
}

// ClearFieldName clears the value of the "field_name" field.
func (_u *TaskHistoryUpdateOne) ClearFieldName() *TaskHistoryUpdateOne {
	_u.mutation.ClearFieldName()
	return _u
}

// SetOldValue sets the "old_value" field.
func (_u *TaskHistoryUpdateOne) SetOldValue(v string) *TaskHistoryUpdateOne {
	_u.mutation.SetOldValue(v)
	return _u
}

// SetNillableOldValue sets the "old_value" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableOldValue(v *string) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetOldValue(*v)
	}
	return _u
}

// ClearOldValue clears the value of the "old_value" field.
func (_u *TaskHistoryUpdateOne) ClearOldValue() *TaskHistoryUpdateOne {
	_u.mutation.ClearOldValue()
	return _u
}

// SetNewValue sets the "new_value" field.
func (_u *TaskHistoryUpdateOne) SetNewValue(v string) *TaskHistoryUpdateOne {
	_u.mutation.SetNewValue(v)
	return _u
}

// SetNillableNewValue sets the "new_value" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableNewValue(v *string) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetNewValue(*v)
	}
	return _u
}

// ClearNewValue clears the value of the "new_value" field.
func (_u *TaskHistoryUpdateOne) ClearNewValue() *TaskHistoryUpdateOne {
	_u.mutation.ClearNewValue()
	return _u
}

// SetDisplayText sets the "display_text" field.
func (_u *TaskHistoryUpdateOne) SetDisplayText(v string) *TaskHistoryUpdateOne {
	_u.mutation.SetDisplayText(v)
	return _u
}

// SetNillableDisplayText sets the "display_text" field if the given value is not nil.
func (_u *TaskHistoryUpdateOne) SetNillableDisplayText(v *string) *TaskHistoryUpdateOne {
	if v != nil {
		_u.SetDisplayText(*v)
	}
	return _u
}

// ClearDisplayText clears the value of the "display_text" field.
func (_u *TaskHistoryUpdateOne) ClearDisplayText() *TaskHistoryUpdateOne {
	_u.mutation.ClearDisplayText()
	return _u
}

// SetTask sets the "task" edge to the Task entity.
func (_u *TaskHistoryUpdateOne) SetTask(v *Task) *TaskHistoryUpdateOne {
	return _u.SetTaskID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *TaskHistoryUpdateOne) SetUserID(id int) *TaskHistoryUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TaskHistoryUpdateOne) SetUser(v *User) *TaskHistoryUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetChangeType sets the "change_type" edge to the ChangeType entity.
func (_u *TaskHistoryUpdateOne) SetChangeType(v *ChangeType) *TaskHistoryUpdateOne {
	return _u.SetChangeTypeID(v.ID)
}

// Mutation returns the TaskHistoryMutation object of the builder.
func (_u *TaskHistoryUpdateOne) Mutation() *TaskHistoryMutation {
	return _u.mutation
}

// ClearTask clears the "task" edge to the Task entity.
func (_u *TaskHistoryUpdateOne) ClearTask() *TaskHistoryUpdateOne {
	_u.mutation.ClearTask()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TaskHistoryUpdateOne) ClearUser() *TaskHistoryUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearChangeType clears the "change_type" edge to the ChangeType entity.
func (_u *TaskHistoryUpdateOne) ClearChangeType() *TaskHistoryUpdateOne {
	_u.mutation.ClearChangeType()
	return _u
}

// Where appends a list predicates to the TaskHistoryUpdate builder.
func (_u *TaskHistoryUpdateOne) Where(ps ...predicate.TaskHistory) *TaskHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskHistoryUpdateOne) Select(field string, fields ...string) *TaskHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskHistory entity.
func (_u *TaskHistoryUpdateOne) Save(ctx context.Context) (*TaskHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskHistoryUpdateOne) SaveX(ctx context.Context) *TaskHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.FieldName(); ok {
		if err := taskhistory.FieldNameValidator(v); err != nil {
			return &ValidationError{Name: "field_name", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.field_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayText(); ok {
		if err := taskhistory.DisplayTextValidator(v); err != nil {
			return &ValidationError{Name: "display_text", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.display_text": %w`, err)}
		}
	}
	if _u.mutation.TaskCleared() && len(_u.mutation.TaskIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskHistory.task"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskHistory.user"`)
	}
	if _u.mutation.ChangeTypeCleared() && len(_u.mutation.ChangeTypeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TaskHistory.change_type"`)
	}
	return nil
}

func (_u *TaskHistoryUpdateOne) sqlSave(ctx context.Context) (_node *TaskHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskhistory.Table, taskhistory.Columns, sqlgraph.NewFieldSpec(taskhistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskhistory.FieldID)
		for _, f := range fields {
			if !taskhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FieldName(); ok {
		_spec.SetField(taskhistory.FieldFieldName, field.TypeString, value)
	}
	if _u.mutation.FieldNameCleared() {
		_spec.ClearField(taskhistory.FieldFieldName, field.TypeString)
	}
	if value, ok := _u.mutation.OldValue(); ok {
		_spec.SetField(taskhistory.FieldOldValue, field.TypeString, value)
	}
	if _u.mutation.OldValueCleared() {
		_spec.ClearField(taskhistory.FieldOldValue, field.TypeString)
	}
	if value, ok := _u.mutation.NewValue(); ok {
		_spec.SetField(taskhistory.FieldNewValue, field.TypeString, value)
	}
	if _u.mutation.NewValueCleared() {
		_spec.ClearField(taskhistory.FieldNewValue, field.TypeString)
	}
	if value, ok := _u.mutation.DisplayText(); ok {
		_spec.SetField(taskhistory.FieldDisplayText, field.TypeString, value)
	}
	if _u.mutation.DisplayTextCleared() {
		_spec.ClearField(taskhistory.FieldDisplayText, field.TypeString)
	}
	if _u.mutation.TaskCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.UserTable,
			Columns: []string{taskhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.UserTable,
			Columns: []string{taskhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangeTypeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.ChangeTypeTable,
			Columns: []string{taskhistory.ChangeTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changetype.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangeTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.ChangeTypeTable,
			Columns: []string{taskhistory.ChangeTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changetype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TaskHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
