// Code generated by ent, DO NOT EDIT.

package ent

import (
	"asutp-server/ent/changetype"
	"asutp-server/ent/task"
	"asutp-server/ent/taskhistory"
	"asutp-server/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskHistoryCreate is the builder for creating a TaskHistory entity.
type TaskHistoryCreate struct {
	config
	mutation *TaskHistoryMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *TaskHistoryCreate) SetTaskID(v int) *TaskHistoryCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetChangedBy sets the "changed_by" field.
func (_c *TaskHistoryCreate) SetChangedBy(v int) *TaskHistoryCreate {
	_c.mutation.SetChangedBy(v)
	return _c
}

// SetChangeTypeID sets the "change_type_id" field.
func (_c *TaskHistoryCreate) SetChangeTypeID(v int) *TaskHistoryCreate {
	_c.mutation.SetChangeTypeID(v)
	return _c
}

// SetFieldName sets the "field_name" field.
func (_c *TaskHistoryCreate) SetFieldName(v string) *TaskHistoryCreate {
	_c.mutation.SetFieldName(v)
	return _c
}

// SetNillableFieldName sets the "field_name" field if the given value is not nil.
func (_c *TaskHistoryCreate) SetNillableFieldName(v *string) *TaskHistoryCreate {
	if v != nil {
		_c.SetFieldName(*v)
	}
	return _c
}

// SetOldValue sets the "old_value" field.
func (_c *TaskHistoryCreate) SetOldValue(v string) *TaskHistoryCreate {
	_c.mutation.SetOldValue(v)
	return _c
}

// SetNillableOldValue sets the "old_value" field if the given value is not nil.
func (_c *TaskHistoryCreate) SetNillableOldValue(v *string) *TaskHistoryCreate {
	if v != nil {
		_c.SetOldValue(*v)
	}
	return _c
}

// SetNewValue sets the "new_value" field.
func (_c *TaskHistoryCreate) SetNewValue(v string) *TaskHistoryCreate {
	_c.mutation.SetNewValue(v)
	return _c
}

// SetNillableNewValue sets the "new_value" field if the given value is not nil.
func (_c *TaskHistoryCreate) SetNillableNewValue(v *string) *TaskHistoryCreate {
	if v != nil {
		_c.SetNewValue(*v)
	}
	return _c
}

// SetDisplayText sets the "display_text" field.
func (_c *TaskHistoryCreate) SetDisplayText(v string) *TaskHistoryCreate {
	_c.mutation.SetDisplayText(v)
	return _c
}

// SetNillableDisplayText sets the "display_text" field if the given value is not nil.
func (_c *TaskHistoryCreate) SetNillableDisplayText(v *string) *TaskHistoryCreate {
	if v != nil {
		_c.SetDisplayText(*v)
	}
	return _c
}

// SetChangedAt sets the "changed_at" field.
func (_c *TaskHistoryCreate) SetChangedAt(v time.Time) *TaskHistoryCreate {
	_c.mutation.SetChangedAt(v)
	return _c
}

// SetNillableChangedAt sets the "changed_at" field if the given value is not nil.
func (_c *TaskHistoryCreate) SetNillableChangedAt(v *time.Time) *TaskHistoryCreate {
	if v != nil {
		_c.SetChangedAt(*v)
	}
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *TaskHistoryCreate) SetTask(v *Task) *TaskHistoryCreate {
	return _c.SetTaskID(v.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *TaskHistoryCreate) SetUserID(id int) *TaskHistoryCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *TaskHistoryCreate) SetUser(v *User) *TaskHistoryCreate {
	return _c.SetUserID(v.ID)
}

// SetChangeType sets the "change_type" edge to the ChangeType entity.
func (_c *TaskHistoryCreate) SetChangeType(v *ChangeType) *TaskHistoryCreate {
	return _c.SetChangeTypeID(v.ID)
}

// Mutation returns the TaskHistoryMutation object of the builder.
func (_c *TaskHistoryCreate) Mutation() *TaskHistoryMutation {
	return _c.mutation
}

// Save creates the TaskHistory in the database.
func (_c *TaskHistoryCreate) Save(ctx context.Context) (*TaskHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskHistoryCreate) SaveX(ctx context.Context) *TaskHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskHistoryCreate) defaults() {
	if _, ok := _c.mutation.ChangedAt(); !ok {
		v := taskhistory.DefaultChangedAt()
		_c.mutation.SetChangedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskHistoryCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "TaskHistory.task_id"`)}
	}
	if _, ok := _c.mutation.ChangedBy(); !ok {
		return &ValidationError{Name: "changed_by", err: errors.New(`ent: missing required field "TaskHistory.changed_by"`)}
	}
	if _, ok := _c.mutation.ChangeTypeID(); !ok {
		return &ValidationError{Name: "change_type_id", err: errors.New(`ent: missing required field "TaskHistory.change_type_id"`)}
	}
	if v, ok := _c.mutation.FieldName(); ok {
		if err := taskhistory.FieldNameValidator(v); err != nil {
			return &ValidationError{Name: "field_name", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.field_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DisplayText(); ok {
		if err := taskhistory.DisplayTextValidator(v); err != nil {
			return &ValidationError{Name: "display_text", err: fmt.Errorf(`ent: validator failed for field "TaskHistory.display_text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChangedAt(); !ok {
		return &ValidationError{Name: "changed_at", err: errors.New(`ent: missing required field "TaskHistory.changed_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskHistory.task"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "TaskHistory.user"`)}
	}
	if len(_c.mutation.ChangeTypeIDs()) == 0 {
		return &ValidationError{Name: "change_type", err: errors.New(`ent: missing required edge "TaskHistory.change_type"`)}
	}
	return nil
}

func (_c *TaskHistoryCreate) sqlSave(ctx context.Context) (*TaskHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskHistoryCreate) createSpec() (*TaskHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskhistory.Table, sqlgraph.NewFieldSpec(taskhistory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.FieldName(); ok {
		_spec.SetField(taskhistory.FieldFieldName, field.TypeString, value)
		_node.FieldName = &value
	}
	if value, ok := _c.mutation.OldValue(); ok {
		_spec.SetField(taskhistory.FieldOldValue, field.TypeString, value)
		_node.OldValue = &value
	}
	if value, ok := _c.mutation.NewValue(); ok {
		_spec.SetField(taskhistory.FieldNewValue, field.TypeString, value)
		_node.NewValue = &value
	}
	if value, ok := _c.mutation.DisplayText(); ok {
		_spec.SetField(taskhistory.FieldDisplayText, field.TypeString, value)
		_node.DisplayText = &value
	}
	if value, ok := _c.mutation.ChangedAt(); ok {
		_spec.SetField(taskhistory.FieldChangedAt, field.TypeTime, value)
		_node.ChangedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.TaskTable,
			Columns: []string{taskhistory.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.UserTable,
			Columns: []string{taskhistory.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChangedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChangeTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskhistory.ChangeTypeTable,
			Columns: []string{taskhistory.ChangeTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(changetype.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChangeTypeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskHistoryCreateBulk is the builder for creating many TaskHistory entities in bulk.
type TaskHistoryCreateBulk struct {
	config
	err      error
	builders []*TaskHistoryCreate
}

// Save creates the TaskHistory entities in the database.
func (_c *TaskHistoryCreateBulk) Save(ctx context.Context) ([]*TaskHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskHistoryCreateBulk) SaveX(ctx context.Context) []*TaskHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
