// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ChangeType is the predicate function for changetype builders.
type ChangeType func(*sql.Selector)

// ExportLog is the predicate function for exportlog builders.
type ExportLog func(*sql.Selector)

// ExportLogTask is the predicate function for exportlogtask builders.
type ExportLogTask func(*sql.Selector)

// ExportType is the predicate function for exporttype builders.
type ExportType func(*sql.Selector)

// Kpi is the predicate function for kpi builders.
type Kpi func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// NotificationSetting is the predicate function for notificationsetting builders.
type NotificationSetting func(*sql.Selector)

// NotificationType is the predicate function for notificationtype builders.
type NotificationType func(*sql.Selector)

// PasswordResetToken is the predicate function for passwordresettoken builders.
type PasswordResetToken func(*sql.Selector)

// Priority is the predicate function for priority builders.
type Priority func(*sql.Selector)

// RefreshToken is the predicate function for refreshtoken builders.
type RefreshToken func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskAssignee is the predicate function for taskassignee builders.
type TaskAssignee func(*sql.Selector)

// TaskCategory is the predicate function for taskcategory builders.
type TaskCategory func(*sql.Selector)

// TaskHistory is the predicate function for taskhistory builders.
type TaskHistory func(*sql.Selector)

// TaskStatus is the predicate function for taskstatus builders.
type TaskStatus func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
