// Code generated by ent, DO NOT EDIT.

package exportlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the exportlog type in the database.
	Label = "export_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldExportTypeID holds the string denoting the export_type_id field in the database.
	FieldExportTypeID = "export_type_id"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldRecordCount holds the string denoting the record_count field in the database.
	FieldRecordCount = "record_count"
	// FieldExportedAt holds the string denoting the exported_at field in the database.
	FieldExportedAt = "exported_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeExportType holds the string denoting the export_type edge name in mutations.
	EdgeExportType = "export_type"
	// EdgeExportLogTasks holds the string denoting the export_log_tasks edge name in mutations.
	EdgeExportLogTasks = "export_log_tasks"
	// Table holds the table name of the exportlog in the database.
	Table = "export_logs"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "export_logs"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ExportTypeTable is the table that holds the export_type relation/edge.
	ExportTypeTable = "export_logs"
	// ExportTypeInverseTable is the table name for the ExportType entity.
	// It exists in this package in order to avoid circular dependency with the "exporttype" package.
	ExportTypeInverseTable = "export_types"
	// ExportTypeColumn is the table column denoting the export_type relation/edge.
	ExportTypeColumn = "export_type_id"
	// ExportLogTasksTable is the table that holds the export_log_tasks relation/edge.
	ExportLogTasksTable = "export_log_tasks"
	// ExportLogTasksInverseTable is the table name for the ExportLogTask entity.
	// It exists in this package in order to avoid circular dependency with the "exportlogtask" package.
	ExportLogTasksInverseTable = "export_log_tasks"
	// ExportLogTasksColumn is the table column denoting the export_log_tasks relation/edge.
	ExportLogTasksColumn = "export_log_id"
)

// Columns holds all SQL columns for exportlog fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldExportTypeID,
	FieldFileName,
	FieldRecordCount,
	FieldExportedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	FileNameValidator func(string) error
	// DefaultExportedAt holds the default value on creation for the "exported_at" field.
	DefaultExportedAt func() time.Time
)

// OrderOption defines the ordering options for the ExportLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByExportTypeID orders the results by the export_type_id field.
func ByExportTypeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExportTypeID, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByRecordCount orders the results by the record_count field.
func ByRecordCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordCount, opts...).ToFunc()
}

// ByExportedAt orders the results by the exported_at field.
func ByExportedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExportedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByExportTypeField orders the results by export_type field.
func ByExportTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExportTypeStep(), sql.OrderByField(field, opts...))
	}
}

// ByExportLogTasksCount orders the results by export_log_tasks count.
func ByExportLogTasksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExportLogTasksStep(), opts...)
	}
}

// ByExportLogTasks orders the results by export_log_tasks terms.
func ByExportLogTasks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExportLogTasksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newExportTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExportTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExportTypeTable, ExportTypeColumn),
	)
}
func newExportLogTasksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExportLogTasksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExportLogTasksTable, ExportLogTasksColumn),
	)
}
