// Code generated by ent, DO NOT EDIT.

package taskcategory

import (
	"asutp-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldName, v))
}

// IconIdentifier applies equality check predicate on the "icon_identifier" field. It's identical to IconIdentifierEQ.
func IconIdentifier(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldIconIdentifier, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldDescription, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldIsActive, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldContainsFold(FieldName, v))
}

// IconIdentifierEQ applies the EQ predicate on the "icon_identifier" field.
func IconIdentifierEQ(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldIconIdentifier, v))
}

// IconIdentifierNEQ applies the NEQ predicate on the "icon_identifier" field.
func IconIdentifierNEQ(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNEQ(FieldIconIdentifier, v))
}

// IconIdentifierIn applies the In predicate on the "icon_identifier" field.
func IconIdentifierIn(vs ...string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldIn(FieldIconIdentifier, vs...))
}

// IconIdentifierNotIn applies the NotIn predicate on the "icon_identifier" field.
func IconIdentifierNotIn(vs ...string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNotIn(FieldIconIdentifier, vs...))
}

// IconIdentifierGT applies the GT predicate on the "icon_identifier" field.
func IconIdentifierGT(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldGT(FieldIconIdentifier, v))
}

// IconIdentifierGTE applies the GTE predicate on the "icon_identifier" field.
func IconIdentifierGTE(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldGTE(FieldIconIdentifier, v))
}

// IconIdentifierLT applies the LT predicate on the "icon_identifier" field.
func IconIdentifierLT(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldLT(FieldIconIdentifier, v))
}

// IconIdentifierLTE applies the LTE predicate on the "icon_identifier" field.
func IconIdentifierLTE(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldLTE(FieldIconIdentifier, v))
}

// IconIdentifierContains applies the Contains predicate on the "icon_identifier" field.
func IconIdentifierContains(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldContains(FieldIconIdentifier, v))
}

// IconIdentifierHasPrefix applies the HasPrefix predicate on the "icon_identifier" field.
func IconIdentifierHasPrefix(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldHasPrefix(FieldIconIdentifier, v))
}

// IconIdentifierHasSuffix applies the HasSuffix predicate on the "icon_identifier" field.
func IconIdentifierHasSuffix(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldHasSuffix(FieldIconIdentifier, v))
}

// IconIdentifierEqualFold applies the EqualFold predicate on the "icon_identifier" field.
func IconIdentifierEqualFold(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEqualFold(FieldIconIdentifier, v))
}

// IconIdentifierContainsFold applies the ContainsFold predicate on the "icon_identifier" field.
func IconIdentifierContainsFold(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldContainsFold(FieldIconIdentifier, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldContainsFold(FieldDescription, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.TaskCategory {
	return predicate.TaskCategory(sql.FieldNEQ(FieldIsActive, v))
}

// HasTasks applies the HasEdge predicate on the "tasks" edge.
func HasTasks() predicate.TaskCategory {
	return predicate.TaskCategory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TasksTable, TasksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTasksWith applies the HasEdge predicate on the "tasks" edge with a given conditions (other predicates).
func HasTasksWith(preds ...predicate.Task) predicate.TaskCategory {
	return predicate.TaskCategory(func(s *sql.Selector) {
		step := newTasksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskCategory) predicate.TaskCategory {
	return predicate.TaskCategory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskCategory) predicate.TaskCategory {
	return predicate.TaskCategory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskCategory) predicate.TaskCategory {
	return predicate.TaskCategory(sql.NotPredicates(p))
}
