// Code generated by ent, DO NOT EDIT.

package taskhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the taskhistory type in the database.
	Label = "task_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldChangedBy holds the string denoting the changed_by field in the database.
	FieldChangedBy = "changed_by"
	// FieldChangeTypeID holds the string denoting the change_type_id field in the database.
	FieldChangeTypeID = "change_type_id"
	// FieldFieldName holds the string denoting the field_name field in the database.
	FieldFieldName = "field_name"
	// FieldOldValue holds the string denoting the old_value field in the database.
	FieldOldValue = "old_value"
	// FieldNewValue holds the string denoting the new_value field in the database.
	FieldNewValue = "new_value"
	// FieldDisplayText holds the string denoting the display_text field in the database.
	FieldDisplayText = "display_text"
	// FieldChangedAt holds the string denoting the changed_at field in the database.
	FieldChangedAt = "changed_at"
	// EdgeTask holds the string denoting the task edge name in mutations.
	EdgeTask = "task"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeChangeType holds the string denoting the change_type edge name in mutations.
	EdgeChangeType = "change_type"
	// Table holds the table name of the taskhistory in the database.
	Table = "task_histories"
	// TaskTable is the table that holds the task relation/edge.
	TaskTable = "task_histories"
	// TaskInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TaskInverseTable = "tasks"
	// TaskColumn is the table column denoting the task relation/edge.
	TaskColumn = "task_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "task_histories"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "changed_by"
	// ChangeTypeTable is the table that holds the change_type relation/edge.
	ChangeTypeTable = "task_histories"
	// ChangeTypeInverseTable is the table name for the ChangeType entity.
	// It exists in this package in order to avoid circular dependency with the "changetype" package.
	ChangeTypeInverseTable = "change_types"
	// ChangeTypeColumn is the table column denoting the change_type relation/edge.
	ChangeTypeColumn = "change_type_id"
)

// Columns holds all SQL columns for taskhistory fields.
var Columns = []string{
	FieldID,
	FieldTaskID,
	FieldChangedBy,
	FieldChangeTypeID,
	FieldFieldName,
	FieldOldValue,
	FieldNewValue,
	FieldDisplayText,
	FieldChangedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FieldNameValidator is a validator for the "field_name" field. It is called by the builders before save.
	FieldNameValidator func(string) error
	// DisplayTextValidator is a validator for the "display_text" field. It is called by the builders before save.
	DisplayTextValidator func(string) error
	// DefaultChangedAt holds the default value on creation for the "changed_at" field.
	DefaultChangedAt func() time.Time
)

// OrderOption defines the ordering options for the TaskHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByChangedBy orders the results by the changed_by field.
func ByChangedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedBy, opts...).ToFunc()
}

// ByChangeTypeID orders the results by the change_type_id field.
func ByChangeTypeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangeTypeID, opts...).ToFunc()
}

// ByFieldName orders the results by the field_name field.
func ByFieldName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFieldName, opts...).ToFunc()
}

// ByOldValue orders the results by the old_value field.
func ByOldValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOldValue, opts...).ToFunc()
}

// ByNewValue orders the results by the new_value field.
func ByNewValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewValue, opts...).ToFunc()
}

// ByDisplayText orders the results by the display_text field.
func ByDisplayText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayText, opts...).ToFunc()
}

// ByChangedAt orders the results by the changed_at field.
func ByChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedAt, opts...).ToFunc()
}

// ByTaskField orders the results by task field.
func ByTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByChangeTypeField orders the results by change_type field.
func ByChangeTypeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChangeTypeStep(), sql.OrderByField(field, opts...))
	}
}
func newTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newChangeTypeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChangeTypeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChangeTypeTable, ChangeTypeColumn),
	)
}
