// Code generated by ent, DO NOT EDIT.

package taskhistory

import (
	"asutp-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLTE(FieldID, id))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldTaskID, v))
}

// ChangedBy applies equality check predicate on the "changed_by" field. It's identical to ChangedByEQ.
func ChangedBy(v int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldChangedBy, v))
}

// ChangeTypeID applies equality check predicate on the "change_type_id" field. It's identical to ChangeTypeIDEQ.
func ChangeTypeID(v int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldChangeTypeID, v))
}

// FieldName applies equality check predicate on the "field_name" field. It's identical to FieldNameEQ.
func FieldName(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldFieldName, v))
}

// OldValue applies equality check predicate on the "old_value" field. It's identical to OldValueEQ.
func OldValue(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldOldValue, v))
}

// NewValue applies equality check predicate on the "new_value" field. It's identical to NewValueEQ.
func NewValue(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldNewValue, v))
}

// DisplayText applies equality check predicate on the "display_text" field. It's identical to DisplayTextEQ.
func DisplayText(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldDisplayText, v))
}

// ChangedAt applies equality check predicate on the "changed_at" field. It's identical to ChangedAtEQ.
func ChangedAt(v time.Time) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldChangedAt, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotIn(FieldTaskID, vs...))
}

// ChangedByEQ applies the EQ predicate on the "changed_by" field.
func ChangedByEQ(v int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldChangedBy, v))
}

// ChangedByNEQ applies the NEQ predicate on the "changed_by" field.
func ChangedByNEQ(v int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNEQ(FieldChangedBy, v))
}

// ChangedByIn applies the In predicate on the "changed_by" field.
func ChangedByIn(vs ...int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIn(FieldChangedBy, vs...))
}

// ChangedByNotIn applies the NotIn predicate on the "changed_by" field.
func ChangedByNotIn(vs ...int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotIn(FieldChangedBy, vs...))
}

// ChangeTypeIDEQ applies the EQ predicate on the "change_type_id" field.
func ChangeTypeIDEQ(v int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldChangeTypeID, v))
}

// ChangeTypeIDNEQ applies the NEQ predicate on the "change_type_id" field.
func ChangeTypeIDNEQ(v int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNEQ(FieldChangeTypeID, v))
}

// ChangeTypeIDIn applies the In predicate on the "change_type_id" field.
func ChangeTypeIDIn(vs ...int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIn(FieldChangeTypeID, vs...))
}

// ChangeTypeIDNotIn applies the NotIn predicate on the "change_type_id" field.
func ChangeTypeIDNotIn(vs ...int) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotIn(FieldChangeTypeID, vs...))
}

// FieldNameEQ applies the EQ predicate on the "field_name" field.
func FieldNameEQ(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldFieldName, v))
}

// FieldNameNEQ applies the NEQ predicate on the "field_name" field.
func FieldNameNEQ(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNEQ(FieldFieldName, v))
}

// FieldNameIn applies the In predicate on the "field_name" field.
func FieldNameIn(vs ...string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIn(FieldFieldName, vs...))
}

// FieldNameNotIn applies the NotIn predicate on the "field_name" field.
func FieldNameNotIn(vs ...string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotIn(FieldFieldName, vs...))
}

// FieldNameGT applies the GT predicate on the "field_name" field.
func FieldNameGT(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGT(FieldFieldName, v))
}

// FieldNameGTE applies the GTE predicate on the "field_name" field.
func FieldNameGTE(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGTE(FieldFieldName, v))
}

// FieldNameLT applies the LT predicate on the "field_name" field.
func FieldNameLT(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLT(FieldFieldName, v))
}

// FieldNameLTE applies the LTE predicate on the "field_name" field.
func FieldNameLTE(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLTE(FieldFieldName, v))
}

// FieldNameContains applies the Contains predicate on the "field_name" field.
func FieldNameContains(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldContains(FieldFieldName, v))
}

// FieldNameHasPrefix applies the HasPrefix predicate on the "field_name" field.
func FieldNameHasPrefix(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldHasPrefix(FieldFieldName, v))
}

// FieldNameHasSuffix applies the HasSuffix predicate on the "field_name" field.
func FieldNameHasSuffix(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldHasSuffix(FieldFieldName, v))
}

// FieldNameIsNil applies the IsNil predicate on the "field_name" field.
func FieldNameIsNil() predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIsNull(FieldFieldName))
}

// FieldNameNotNil applies the NotNil predicate on the "field_name" field.
func FieldNameNotNil() predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotNull(FieldFieldName))
}

// FieldNameEqualFold applies the EqualFold predicate on the "field_name" field.
func FieldNameEqualFold(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEqualFold(FieldFieldName, v))
}

// FieldNameContainsFold applies the ContainsFold predicate on the "field_name" field.
func FieldNameContainsFold(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldContainsFold(FieldFieldName, v))
}

// OldValueEQ applies the EQ predicate on the "old_value" field.
func OldValueEQ(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldOldValue, v))
}

// OldValueNEQ applies the NEQ predicate on the "old_value" field.
func OldValueNEQ(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNEQ(FieldOldValue, v))
}

// OldValueIn applies the In predicate on the "old_value" field.
func OldValueIn(vs ...string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIn(FieldOldValue, vs...))
}

// OldValueNotIn applies the NotIn predicate on the "old_value" field.
func OldValueNotIn(vs ...string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotIn(FieldOldValue, vs...))
}

// OldValueGT applies the GT predicate on the "old_value" field.
func OldValueGT(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGT(FieldOldValue, v))
}

// OldValueGTE applies the GTE predicate on the "old_value" field.
func OldValueGTE(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGTE(FieldOldValue, v))
}

// OldValueLT applies the LT predicate on the "old_value" field.
func OldValueLT(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLT(FieldOldValue, v))
}

// OldValueLTE applies the LTE predicate on the "old_value" field.
func OldValueLTE(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLTE(FieldOldValue, v))
}

// OldValueContains applies the Contains predicate on the "old_value" field.
func OldValueContains(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldContains(FieldOldValue, v))
}

// OldValueHasPrefix applies the HasPrefix predicate on the "old_value" field.
func OldValueHasPrefix(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldHasPrefix(FieldOldValue, v))
}

// OldValueHasSuffix applies the HasSuffix predicate on the "old_value" field.
func OldValueHasSuffix(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldHasSuffix(FieldOldValue, v))
}

// OldValueIsNil applies the IsNil predicate on the "old_value" field.
func OldValueIsNil() predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIsNull(FieldOldValue))
}

// OldValueNotNil applies the NotNil predicate on the "old_value" field.
func OldValueNotNil() predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotNull(FieldOldValue))
}

// OldValueEqualFold applies the EqualFold predicate on the "old_value" field.
func OldValueEqualFold(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEqualFold(FieldOldValue, v))
}

// OldValueContainsFold applies the ContainsFold predicate on the "old_value" field.
func OldValueContainsFold(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldContainsFold(FieldOldValue, v))
}

// NewValueEQ applies the EQ predicate on the "new_value" field.
func NewValueEQ(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldNewValue, v))
}

// NewValueNEQ applies the NEQ predicate on the "new_value" field.
func NewValueNEQ(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNEQ(FieldNewValue, v))
}

// NewValueIn applies the In predicate on the "new_value" field.
func NewValueIn(vs ...string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIn(FieldNewValue, vs...))
}

// NewValueNotIn applies the NotIn predicate on the "new_value" field.
func NewValueNotIn(vs ...string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotIn(FieldNewValue, vs...))
}

// NewValueGT applies the GT predicate on the "new_value" field.
func NewValueGT(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGT(FieldNewValue, v))
}

// NewValueGTE applies the GTE predicate on the "new_value" field.
func NewValueGTE(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGTE(FieldNewValue, v))
}

// NewValueLT applies the LT predicate on the "new_value" field.
func NewValueLT(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLT(FieldNewValue, v))
}

// NewValueLTE applies the LTE predicate on the "new_value" field.
func NewValueLTE(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLTE(FieldNewValue, v))
}

// NewValueContains applies the Contains predicate on the "new_value" field.
func NewValueContains(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldContains(FieldNewValue, v))
}

// NewValueHasPrefix applies the HasPrefix predicate on the "new_value" field.
func NewValueHasPrefix(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldHasPrefix(FieldNewValue, v))
}

// NewValueHasSuffix applies the HasSuffix predicate on the "new_value" field.
func NewValueHasSuffix(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldHasSuffix(FieldNewValue, v))
}

// NewValueIsNil applies the IsNil predicate on the "new_value" field.
func NewValueIsNil() predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIsNull(FieldNewValue))
}

// NewValueNotNil applies the NotNil predicate on the "new_value" field.
func NewValueNotNil() predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotNull(FieldNewValue))
}

// NewValueEqualFold applies the EqualFold predicate on the "new_value" field.
func NewValueEqualFold(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEqualFold(FieldNewValue, v))
}

// NewValueContainsFold applies the ContainsFold predicate on the "new_value" field.
func NewValueContainsFold(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldContainsFold(FieldNewValue, v))
}

// DisplayTextEQ applies the EQ predicate on the "display_text" field.
func DisplayTextEQ(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldDisplayText, v))
}

// DisplayTextNEQ applies the NEQ predicate on the "display_text" field.
func DisplayTextNEQ(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNEQ(FieldDisplayText, v))
}

// DisplayTextIn applies the In predicate on the "display_text" field.
func DisplayTextIn(vs ...string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIn(FieldDisplayText, vs...))
}

// DisplayTextNotIn applies the NotIn predicate on the "display_text" field.
func DisplayTextNotIn(vs ...string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotIn(FieldDisplayText, vs...))
}

// DisplayTextGT applies the GT predicate on the "display_text" field.
func DisplayTextGT(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGT(FieldDisplayText, v))
}

// DisplayTextGTE applies the GTE predicate on the "display_text" field.
func DisplayTextGTE(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGTE(FieldDisplayText, v))
}

// DisplayTextLT applies the LT predicate on the "display_text" field.
func DisplayTextLT(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLT(FieldDisplayText, v))
}

// DisplayTextLTE applies the LTE predicate on the "display_text" field.
func DisplayTextLTE(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLTE(FieldDisplayText, v))
}

// DisplayTextContains applies the Contains predicate on the "display_text" field.
func DisplayTextContains(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldContains(FieldDisplayText, v))
}

// DisplayTextHasPrefix applies the HasPrefix predicate on the "display_text" field.
func DisplayTextHasPrefix(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldHasPrefix(FieldDisplayText, v))
}

// DisplayTextHasSuffix applies the HasSuffix predicate on the "display_text" field.
func DisplayTextHasSuffix(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldHasSuffix(FieldDisplayText, v))
}

// DisplayTextIsNil applies the IsNil predicate on the "display_text" field.
func DisplayTextIsNil() predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIsNull(FieldDisplayText))
}

// DisplayTextNotNil applies the NotNil predicate on the "display_text" field.
func DisplayTextNotNil() predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotNull(FieldDisplayText))
}

// DisplayTextEqualFold applies the EqualFold predicate on the "display_text" field.
func DisplayTextEqualFold(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEqualFold(FieldDisplayText, v))
}

// DisplayTextContainsFold applies the ContainsFold predicate on the "display_text" field.
func DisplayTextContainsFold(v string) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldContainsFold(FieldDisplayText, v))
}

// ChangedAtEQ applies the EQ predicate on the "changed_at" field.
func ChangedAtEQ(v time.Time) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldEQ(FieldChangedAt, v))
}

// ChangedAtNEQ applies the NEQ predicate on the "changed_at" field.
func ChangedAtNEQ(v time.Time) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNEQ(FieldChangedAt, v))
}

// ChangedAtIn applies the In predicate on the "changed_at" field.
func ChangedAtIn(vs ...time.Time) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldIn(FieldChangedAt, vs...))
}

// ChangedAtNotIn applies the NotIn predicate on the "changed_at" field.
func ChangedAtNotIn(vs ...time.Time) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldNotIn(FieldChangedAt, vs...))
}

// ChangedAtGT applies the GT predicate on the "changed_at" field.
func ChangedAtGT(v time.Time) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGT(FieldChangedAt, v))
}

// ChangedAtGTE applies the GTE predicate on the "changed_at" field.
func ChangedAtGTE(v time.Time) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldGTE(FieldChangedAt, v))
}

// ChangedAtLT applies the LT predicate on the "changed_at" field.
func ChangedAtLT(v time.Time) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLT(FieldChangedAt, v))
}

// ChangedAtLTE applies the LTE predicate on the "changed_at" field.
func ChangedAtLTE(v time.Time) predicate.TaskHistory {
	return predicate.TaskHistory(sql.FieldLTE(FieldChangedAt, v))
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.TaskHistory {
	return predicate.TaskHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.TaskHistory {
	return predicate.TaskHistory(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.TaskHistory {
	return predicate.TaskHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.TaskHistory {
	return predicate.TaskHistory(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChangeType applies the HasEdge predicate on the "change_type" edge.
func HasChangeType() predicate.TaskHistory {
	return predicate.TaskHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChangeTypeTable, ChangeTypeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChangeTypeWith applies the HasEdge predicate on the "change_type" edge with a given conditions (other predicates).
func HasChangeTypeWith(preds ...predicate.ChangeType) predicate.TaskHistory {
	return predicate.TaskHistory(func(s *sql.Selector) {
		step := newChangeTypeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskHistory) predicate.TaskHistory {
	return predicate.TaskHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskHistory) predicate.TaskHistory {
	return predicate.TaskHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskHistory) predicate.TaskHistory {
	return predicate.TaskHistory(sql.NotPredicates(p))
}
