// Code generated by ent, DO NOT EDIT.

package exportlogtask

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the exportlogtask type in the database.
	Label = "export_log_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExportLogID holds the string denoting the export_log_id field in the database.
	FieldExportLogID = "export_log_id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// EdgeExportLog holds the string denoting the export_log edge name in mutations.
	EdgeExportLog = "export_log"
	// EdgeTask holds the string denoting the task edge name in mutations.
	EdgeTask = "task"
	// Table holds the table name of the exportlogtask in the database.
	Table = "export_log_tasks"
	// ExportLogTable is the table that holds the export_log relation/edge.
	ExportLogTable = "export_log_tasks"
	// ExportLogInverseTable is the table name for the ExportLog entity.
	// It exists in this package in order to avoid circular dependency with the "exportlog" package.
	ExportLogInverseTable = "export_logs"
	// ExportLogColumn is the table column denoting the export_log relation/edge.
	ExportLogColumn = "export_log_id"
	// TaskTable is the table that holds the task relation/edge.
	TaskTable = "export_log_tasks"
	// TaskInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TaskInverseTable = "tasks"
	// TaskColumn is the table column denoting the task relation/edge.
	TaskColumn = "task_id"
)

// Columns holds all SQL columns for exportlogtask fields.
var Columns = []string{
	FieldID,
	FieldExportLogID,
	FieldTaskID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ExportLogTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByExportLogID orders the results by the export_log_id field.
func ByExportLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExportLogID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByExportLogField orders the results by export_log field.
func ByExportLogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExportLogStep(), sql.OrderByField(field, opts...))
	}
}

// ByTaskField orders the results by task field.
func ByTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskStep(), sql.OrderByField(field, opts...))
	}
}
func newExportLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExportLogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExportLogTable, ExportLogColumn),
	)
}
func newTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TaskTable, TaskColumn),
	)
}
