// Code generated by ent, DO NOT EDIT.

package exportlogtask

import (
	"asutp-server/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldLTE(FieldID, id))
}

// ExportLogID applies equality check predicate on the "export_log_id" field. It's identical to ExportLogIDEQ.
func ExportLogID(v int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldEQ(FieldExportLogID, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldEQ(FieldTaskID, v))
}

// ExportLogIDEQ applies the EQ predicate on the "export_log_id" field.
func ExportLogIDEQ(v int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldEQ(FieldExportLogID, v))
}

// ExportLogIDNEQ applies the NEQ predicate on the "export_log_id" field.
func ExportLogIDNEQ(v int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldNEQ(FieldExportLogID, v))
}

// ExportLogIDIn applies the In predicate on the "export_log_id" field.
func ExportLogIDIn(vs ...int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldIn(FieldExportLogID, vs...))
}

// ExportLogIDNotIn applies the NotIn predicate on the "export_log_id" field.
func ExportLogIDNotIn(vs ...int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldNotIn(FieldExportLogID, vs...))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.FieldNotIn(FieldTaskID, vs...))
}

// HasExportLog applies the HasEdge predicate on the "export_log" edge.
func HasExportLog() predicate.ExportLogTask {
	return predicate.ExportLogTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ExportLogTable, ExportLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExportLogWith applies the HasEdge predicate on the "export_log" edge with a given conditions (other predicates).
func HasExportLogWith(preds ...predicate.ExportLog) predicate.ExportLogTask {
	return predicate.ExportLogTask(func(s *sql.Selector) {
		step := newExportLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.ExportLogTask {
	return predicate.ExportLogTask(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.ExportLogTask {
	return predicate.ExportLogTask(func(s *sql.Selector) {
		step := newTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExportLogTask) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExportLogTask) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExportLogTask) predicate.ExportLogTask {
	return predicate.ExportLogTask(sql.NotPredicates(p))
}
