// Code generated by ent, DO NOT EDIT.

package notificationsetting

import (
	"asutp-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldUserID, v))
}

// PushEnabled applies equality check predicate on the "push_enabled" field. It's identical to PushEnabledEQ.
func PushEnabled(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldPushEnabled, v))
}

// SoundEnabled applies equality check predicate on the "sound_enabled" field. It's identical to SoundEnabledEQ.
func SoundEnabled(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldSoundEnabled, v))
}

// VibrationEnabled applies equality check predicate on the "vibration_enabled" field. It's identical to VibrationEnabledEQ.
func VibrationEnabled(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldVibrationEnabled, v))
}

// ReminderDaysBefore applies equality check predicate on the "reminder_days_before" field. It's identical to ReminderDaysBeforeEQ.
func ReminderDaysBefore(v int16) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldReminderDaysBefore, v))
}

// QuietHoursStart applies equality check predicate on the "quiet_hours_start" field. It's identical to QuietHoursStartEQ.
func QuietHoursStart(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldQuietHoursStart, v))
}

// QuietHoursEnd applies equality check predicate on the "quiet_hours_end" field. It's identical to QuietHoursEndEQ.
func QuietHoursEnd(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldQuietHoursEnd, v))
}

// NotifyHighPriority applies equality check predicate on the "notify_high_priority" field. It's identical to NotifyHighPriorityEQ.
func NotifyHighPriority(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyHighPriority, v))
}

// NotifyMediumPriority applies equality check predicate on the "notify_medium_priority" field. It's identical to NotifyMediumPriorityEQ.
func NotifyMediumPriority(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyMediumPriority, v))
}

// NotifyLowPriority applies equality check predicate on the "notify_low_priority" field. It's identical to NotifyLowPriorityEQ.
func NotifyLowPriority(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyLowPriority, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldUserID, vs...))
}

// PushEnabledEQ applies the EQ predicate on the "push_enabled" field.
func PushEnabledEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldPushEnabled, v))
}

// PushEnabledNEQ applies the NEQ predicate on the "push_enabled" field.
func PushEnabledNEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldPushEnabled, v))
}

// SoundEnabledEQ applies the EQ predicate on the "sound_enabled" field.
func SoundEnabledEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldSoundEnabled, v))
}

// SoundEnabledNEQ applies the NEQ predicate on the "sound_enabled" field.
func SoundEnabledNEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldSoundEnabled, v))
}

// VibrationEnabledEQ applies the EQ predicate on the "vibration_enabled" field.
func VibrationEnabledEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldVibrationEnabled, v))
}

// VibrationEnabledNEQ applies the NEQ predicate on the "vibration_enabled" field.
func VibrationEnabledNEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldVibrationEnabled, v))
}

// ReminderDaysBeforeEQ applies the EQ predicate on the "reminder_days_before" field.
func ReminderDaysBeforeEQ(v int16) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldReminderDaysBefore, v))
}

// ReminderDaysBeforeNEQ applies the NEQ predicate on the "reminder_days_before" field.
func ReminderDaysBeforeNEQ(v int16) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldReminderDaysBefore, v))
}

// ReminderDaysBeforeIn applies the In predicate on the "reminder_days_before" field.
func ReminderDaysBeforeIn(vs ...int16) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldReminderDaysBefore, vs...))
}

// ReminderDaysBeforeNotIn applies the NotIn predicate on the "reminder_days_before" field.
func ReminderDaysBeforeNotIn(vs ...int16) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldReminderDaysBefore, vs...))
}

// ReminderDaysBeforeGT applies the GT predicate on the "reminder_days_before" field.
func ReminderDaysBeforeGT(v int16) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldReminderDaysBefore, v))
}

// ReminderDaysBeforeGTE applies the GTE predicate on the "reminder_days_before" field.
func ReminderDaysBeforeGTE(v int16) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldReminderDaysBefore, v))
}

// ReminderDaysBeforeLT applies the LT predicate on the "reminder_days_before" field.
func ReminderDaysBeforeLT(v int16) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldReminderDaysBefore, v))
}

// ReminderDaysBeforeLTE applies the LTE predicate on the "reminder_days_before" field.
func ReminderDaysBeforeLTE(v int16) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldReminderDaysBefore, v))
}

// QuietHoursStartEQ applies the EQ predicate on the "quiet_hours_start" field.
func QuietHoursStartEQ(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldQuietHoursStart, v))
}

// QuietHoursStartNEQ applies the NEQ predicate on the "quiet_hours_start" field.
func QuietHoursStartNEQ(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldQuietHoursStart, v))
}

// QuietHoursStartIn applies the In predicate on the "quiet_hours_start" field.
func QuietHoursStartIn(vs ...string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldQuietHoursStart, vs...))
}

// QuietHoursStartNotIn applies the NotIn predicate on the "quiet_hours_start" field.
func QuietHoursStartNotIn(vs ...string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldQuietHoursStart, vs...))
}

// QuietHoursStartGT applies the GT predicate on the "quiet_hours_start" field.
func QuietHoursStartGT(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldQuietHoursStart, v))
}

// QuietHoursStartGTE applies the GTE predicate on the "quiet_hours_start" field.
func QuietHoursStartGTE(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldQuietHoursStart, v))
}

// QuietHoursStartLT applies the LT predicate on the "quiet_hours_start" field.
func QuietHoursStartLT(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldQuietHoursStart, v))
}

// QuietHoursStartLTE applies the LTE predicate on the "quiet_hours_start" field.
func QuietHoursStartLTE(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldQuietHoursStart, v))
}

// QuietHoursStartContains applies the Contains predicate on the "quiet_hours_start" field.
func QuietHoursStartContains(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldContains(FieldQuietHoursStart, v))
}

// QuietHoursStartHasPrefix applies the HasPrefix predicate on the "quiet_hours_start" field.
func QuietHoursStartHasPrefix(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldHasPrefix(FieldQuietHoursStart, v))
}

// QuietHoursStartHasSuffix applies the HasSuffix predicate on the "quiet_hours_start" field.
func QuietHoursStartHasSuffix(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldHasSuffix(FieldQuietHoursStart, v))
}

// QuietHoursStartEqualFold applies the EqualFold predicate on the "quiet_hours_start" field.
func QuietHoursStartEqualFold(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEqualFold(FieldQuietHoursStart, v))
}

// QuietHoursStartContainsFold applies the ContainsFold predicate on the "quiet_hours_start" field.
func QuietHoursStartContainsFold(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldContainsFold(FieldQuietHoursStart, v))
}

// QuietHoursEndEQ applies the EQ predicate on the "quiet_hours_end" field.
func QuietHoursEndEQ(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldQuietHoursEnd, v))
}

// QuietHoursEndNEQ applies the NEQ predicate on the "quiet_hours_end" field.
func QuietHoursEndNEQ(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldQuietHoursEnd, v))
}

// QuietHoursEndIn applies the In predicate on the "quiet_hours_end" field.
func QuietHoursEndIn(vs ...string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldQuietHoursEnd, vs...))
}

// QuietHoursEndNotIn applies the NotIn predicate on the "quiet_hours_end" field.
func QuietHoursEndNotIn(vs ...string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldQuietHoursEnd, vs...))
}

// QuietHoursEndGT applies the GT predicate on the "quiet_hours_end" field.
func QuietHoursEndGT(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldQuietHoursEnd, v))
}

// QuietHoursEndGTE applies the GTE predicate on the "quiet_hours_end" field.
func QuietHoursEndGTE(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldQuietHoursEnd, v))
}

// QuietHoursEndLT applies the LT predicate on the "quiet_hours_end" field.
func QuietHoursEndLT(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldQuietHoursEnd, v))
}

// QuietHoursEndLTE applies the LTE predicate on the "quiet_hours_end" field.
func QuietHoursEndLTE(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldQuietHoursEnd, v))
}

// QuietHoursEndContains applies the Contains predicate on the "quiet_hours_end" field.
func QuietHoursEndContains(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldContains(FieldQuietHoursEnd, v))
}

// QuietHoursEndHasPrefix applies the HasPrefix predicate on the "quiet_hours_end" field.
func QuietHoursEndHasPrefix(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldHasPrefix(FieldQuietHoursEnd, v))
}

// QuietHoursEndHasSuffix applies the HasSuffix predicate on the "quiet_hours_end" field.
func QuietHoursEndHasSuffix(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldHasSuffix(FieldQuietHoursEnd, v))
}

// QuietHoursEndEqualFold applies the EqualFold predicate on the "quiet_hours_end" field.
func QuietHoursEndEqualFold(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEqualFold(FieldQuietHoursEnd, v))
}

// QuietHoursEndContainsFold applies the ContainsFold predicate on the "quiet_hours_end" field.
func QuietHoursEndContainsFold(v string) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldContainsFold(FieldQuietHoursEnd, v))
}

// NotifyHighPriorityEQ applies the EQ predicate on the "notify_high_priority" field.
func NotifyHighPriorityEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyHighPriority, v))
}

// NotifyHighPriorityNEQ applies the NEQ predicate on the "notify_high_priority" field.
func NotifyHighPriorityNEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldNotifyHighPriority, v))
}

// NotifyMediumPriorityEQ applies the EQ predicate on the "notify_medium_priority" field.
func NotifyMediumPriorityEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyMediumPriority, v))
}

// NotifyMediumPriorityNEQ applies the NEQ predicate on the "notify_medium_priority" field.
func NotifyMediumPriorityNEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldNotifyMediumPriority, v))
}

// NotifyLowPriorityEQ applies the EQ predicate on the "notify_low_priority" field.
func NotifyLowPriorityEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldNotifyLowPriority, v))
}

// NotifyLowPriorityNEQ applies the NEQ predicate on the "notify_low_priority" field.
func NotifyLowPriorityNEQ(v bool) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldNotifyLowPriority, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.NotificationSetting {
	return predicate.NotificationSetting(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.NotificationSetting {
	return predicate.NotificationSetting(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationSetting) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationSetting) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationSetting) predicate.NotificationSetting {
	return predicate.NotificationSetting(sql.NotPredicates(p))
}
